// Default seed data — loaded only on first run; after that, sets live in localStorage.
const DEFAULT_SETS = [
  // ---------------- NOUNS ----------------
  {
    name: "NOUNS - common (pt. 1) - people & family",
    terms: [
      { en: "The man", es: "el hombre" },
      { en: "The woman", es: "la mujer" },
      { en: "The boy", es: "el niño" },
      { en: "The girl", es: "la niña" },
      { en: "The friend", es: "el amigo / la amiga" },
      { en: "The family", es: "la familia" },
      { en: "The mother", es: "la madre" },
      { en: "The father", es: "el padre" },
      { en: "The parents", es: "los padres" },
      { en: "The brother", es: "el hermano" },
      { en: "The sister", es: "la hermana" },
      { en: "The half brother", es: "el medio hermano" },
      { en: "The half sister", es: "la media hermana" },
      { en: "The son", es: "el hijo" },
      { en: "The daughter", es: "la hija" },
      { en: "The child", es: "el niño / la niña" },
      { en: "The boyfriend", es: "el novio" },
      { en: "The girlfriend", es: "la novia" },
      { en: "The husband", es: "el marido" },
      { en: "The wife", es: "la esposa" },
      { en: "The grandmother", es: "la abuela" },
      { en: "The grandfather", es: "el abuelo" },
      { en: "The granddaughter", es: "la nieta" },
      { en: "The grandson", es: "el nieto" },
      { en: "The aunt", es: "la tía" },
      { en: "The uncle", es: "el tío" },
      { en: "The cousin", es: "el primo / la prima" },
    ],
  },
  {
    name: "NOUNS - common (pt. 2) - places",
    terms: [
      { en: "House", es: "La casa" },
      { en: "Apartment", es: "El apartamento" },
      { en: "Hotel", es: "El hotel" },
      { en: "Restaurant", es: "El restaurante" },
      { en: "Store", es: "La tienda" },
      { en: "Gym", es: "El gimnasio" },
      { en: "Beach", es: "La playa" },
      { en: "Park", es: "El parque" },
      { en: "Airport", es: "El aeropuerto" },
      { en: "Village", es: "El pueblo" },
      { en: "City", es: "La ciudad" },
      { en: "State", es: "El estado" },
      { en: "Country", es: "El país" },
      { en: "World", es: "El mundo" },
      { en: "School", es: "La escuela" },
      { en: "University", es: "La universidad" },
      { en: "Office", es: "La oficina" },
    ],
  },
  {
    name: "NOUNS - common (pt. 3) - body parts",
    terms: [
      { en: "The head", es: "la cabeza" },
      { en: "The face", es: "la cara" },
      { en: "The eye", es: "el ojo" },
      { en: "The eyes", es: "los ojos" },
      { en: "The nose", es: "la nariz" },
      { en: "The mouth", es: "la boca" },
      { en: "The ear", es: "la oreja" },
      { en: "The hair", es: "el pelo" },
      { en: "The neck", es: "el cuello" },
      { en: "The shoulder", es: "el hombro" },
      { en: "The arm", es: "el brazo" },
      { en: "The hand", es: "la mano" },
      { en: "The leg", es: "la pierna" },
      { en: "The foot", es: "el pie" },
      { en: "The back", es: "la espalda" },
      { en: "The vagina", es: "la vagina" },
      { en: "The breasts", es: "los senos" },
      { en: "The penis", es: "el pene" },
      { en: "The testicles", es: "los testículos" },
      { en: "The butt", es: "el trasero" },
      { en: "The elbow", es: "el codo" },
      { en: "The lips", es: "los labios" },
      { en: "The teeth", es: "los dientes" },
      { en: "The tongue", es: "la lengua" },
      { en: "The tattoo", es: "el tatuaje" },
    ],
  },
  {
    name: "NOUNS - common (pt. 4)",
    terms: [
      { en: "The food", es: "La comida" },
      { en: "The water", es: "El agua" },
      { en: "The coffee", es: "El café" },
      { en: "The beer", es: "La cerveza" },
      { en: "The wine", es: "El vino" },
      { en: "The money", es: "El dinero" },
      { en: "The phone", es: "El teléfono" },
      { en: "The car", es: "El carro" },
      { en: "The bus", es: "El autobús" },
      { en: "The street", es: "La calle" },
      { en: "The door", es: "La puerta" },
      { en: "The window", es: "La ventana" },
      { en: "The table", es: "La mesa" },
      { en: "The chair", es: "La silla" },
      { en: "The bed", es: "La cama" },
      { en: "The bathroom", es: "El baño" },
      { en: "The kitchen", es: "La cocina" },
      { en: "The room", es: "La habitación" },
      { en: "The bag", es: "La bolsa" },
      { en: "The key", es: "La llave" },
    ],
  },
  {
    name: "NOUNS - common (pt. 5)",
    terms: [
      { en: "The clothes", es: "La ropa" },
      { en: "The shirt", es: "La camisa" },
      { en: "The pants", es: "Los pantalones" },
      { en: "The shoes", es: "Los zapatos" },
      { en: "The jacket", es: "La chaqueta" },
      { en: "The hat", es: "El sombrero" },
      { en: "The sock", es: "El calcetín" },
      { en: "The dress", es: "El vestido" },
      { en: "The shorts", es: "Los pantalones cortos" },
      { en: "The underwear", es: "La ropa interior" },
      { en: "The backpack", es: "La mochila" },
      { en: "The suitcase", es: "La maleta" },
      { en: "The passport", es: "El pasaporte" },
      { en: "The ticket", es: "El boleto" },
      { en: "The map", es: "El mapa" },
      { en: "The market", es: "El mercado" },
      { en: "The hospital", es: "El hospital" },
      { en: "The pharmacy", es: "La farmacia" },
      { en: "The church", es: "La iglesia" },
      { en: "The mountain", es: "La montaña" },
      { en: "The river", es: "El río" },
    ],
  },
  {
    name: "NOUNS - common (pt. 6)",
    terms: [
      { en: "The breakfast", es: "El desayuno" },
      { en: "The lunch", es: "El almuerzo" },
      { en: "The dinner", es: "La cena" },
      { en: "The meat", es: "La carne" },
      { en: "The chicken", es: "El pollo" },
      { en: "The fish", es: "El pescado" },
      { en: "The rice", es: "El arroz" },
      { en: "The bread", es: "El pan" },
      { en: "The egg", es: "El huevo" },
      { en: "The cheese", es: "El queso" },
      { en: "The fruit", es: "La fruta" },
      { en: "The vegetable", es: "La verdura" },
      { en: "The soup", es: "La sopa" },
      { en: "The salad", es: "La ensalada" },
      { en: "The dessert", es: "El postre" },
      { en: "The juice", es: "El jugo" },
      { en: "The milk", es: "La leche" },
      { en: "The ice", es: "El hielo" },
      { en: "The bill / check", es: "La cuenta" },
      { en: "The tip", es: "La propina" },
    ],
  },
  {
    name: "NOUNS - common (pt. 7) - more people",
    terms: [
      { en: "The doctor", es: "El doctor / La doctora" },
      { en: "The teacher", es: "El profesor / La profesora" },
      { en: "The waiter", es: "El mesero / La mesera" },
      { en: "The police officer", es: "El policía / La mujer policía" },
      { en: "The driver", es: "El conductor / La conductora" },
      { en: "The cook / chef", es: "El cocinero / La cocinera" },
      { en: "The engineer", es: "El ingeniero / La ingeniera" },
      { en: "The lawyer", es: "El abogado / La abogada" },
      { en: "The nurse", es: "El enfermero / La enfermera" },
      { en: "The student", es: "El estudiante / La estudiante" },
      { en: "The tourist", es: "El turista / La turista" },
      { en: "The stranger", es: "El desconocido / La desconocida" },
      { en: "The neighbor", es: "El vecino / La vecina" },
      { en: "The boss", es: "El jefe / La jefa" },
      { en: "The employee", es: "El empleado / La empleada" },
      { en: "The owner", es: "El dueño / La dueña" },
      { en: "The customer", es: "El cliente / La clienta" },
      { en: "The guide", es: "El guía / La guía" },
      { en: "The artist", es: "El artista / La artista" },
      { en: "The musician", es: "El músico / La música" },
    ],
  },
  {
    name: "NOUNS - common (pt. 8) - more places",
    terms: [
      { en: "The pool", es: "La piscina" },
      { en: "The lake", es: "El lago" },
      { en: "The ocean", es: "El océano" },
      { en: "The forest", es: "El bosque" },
      { en: "The desert", es: "El desierto" },
      { en: "The island", es: "La isla" },
      { en: "The bridge", es: "El puente" },
      { en: "The museum", es: "El museo" },
      { en: "The library", es: "La biblioteca" },
      { en: "The bank", es: "El banco" },
      { en: "The stadium", es: "El estadio" },
      { en: "The theater", es: "El teatro" },
      { en: "The cinema", es: "El cine" },
      { en: "The temple", es: "El templo" },
      { en: "The castle", es: "El castillo" },
      { en: "The volcano", es: "El volcán" },
      { en: "The waterfall", es: "La cascada" },
      { en: "The cave", es: "La cueva" },
      { en: "The border", es: "La frontera" },
      { en: "The neighborhood", es: "El barrio" },
    ],
  },
  {
    name: "NOUNS - common (pt. 9)",
    terms: [
      { en: "The computer", es: "La computadora" },
      { en: "The internet", es: "El internet" },
      { en: "The message", es: "El mensaje" },
      { en: "The password", es: "La contraseña" },
      { en: "The battery", es: "La batería" },
      { en: "The charger", es: "El cargador" },
      { en: "The weather", es: "El clima" },
      { en: "The sun", es: "El sol" },
      { en: "The rain", es: "La lluvia" },
      { en: "The wind", es: "El viento" },
      { en: "The cloud", es: "La nube" },
      { en: "The sky", es: "El cielo" },
      { en: "The star", es: "La estrella" },
      { en: "The moon", es: "La luna" },
      { en: "The towel", es: "La toalla" },
      { en: "The sunscreen", es: "El protector solar" },
      { en: "The glasses", es: "Las gafas" },
      { en: "The camera", es: "La cámara" },
      { en: "The picture", es: "La foto" },
      { en: "The video", es: "El video" },
    ],
  },
  {
    name: "NOUNS - common (pt. 10)",
    terms: [
      { en: "The problem", es: "El problema" },
      { en: "The idea", es: "La idea" },
      { en: "The plan", es: "El plan" },
      { en: "The reason", es: "La razón" },
      { en: "The truth", es: "La verdad" },
      { en: "The lie", es: "La mentira" },
      { en: "The secret", es: "El secreto" },
      { en: "The question", es: "La pregunta" },
      { en: "The answer", es: "La respuesta" },
      { en: "The list", es: "La lista" },
      { en: "The rule", es: "La regla" },
      { en: "The example", es: "El ejemplo" },
      { en: "The mistake", es: "El error" },
      { en: "The surprise", es: "La sorpresa" },
      { en: "The gift", es: "El regalo" },
      { en: "The party", es: "La fiesta" },
      { en: "The trip", es: "El viaje" },
      { en: "The itinerary", es: "El itinerario" },
      { en: "The luggage", es: "El equipaje" },
      { en: "The flight", es: "El vuelo" },
    ],
  },

  // ---------------- VERBS ----------------
  {
    name: "VERBS - conjugations by tense",
    terms: [
      { en: "-ar verbs (preterite endings)", es: "-é, -aste, -ó, -amos, -aron" },
      { en: "-ar verbs (present endings)", es: "-o, -as, -a, -amos, -an" },
      { en: "-er verbs (preterite endings)", es: "-í, -iste, -ió, -imos, -ieron" },
      { en: "-er verbs (present endings)", es: "-o, -es, -e, -emos, -en" },
      { en: "-ir verbs (preterite endings)", es: "-í, -iste, -ió, -imos, -ieron" },
      { en: "-ir verbs (present endings)", es: "-o, -es, -e, -imos, -en" },
    ],
  },
  {
    name: "VERBS - irregular",
    terms: [
      { en: "To be (permanent)", es: "Ser", note: "Present: soy, eres, es, somos, son | Preterite: fui, fuiste, fue, fuimos, fueron" },
      { en: "To be (temporary)", es: "Estar", note: "Present: estoy, estás, está, estamos, están | Preterite: estuve, estuviste, estuvo, estuvimos, estuvieron" },
      { en: "To have", es: "Tener", note: "Present: tengo, tienes, tiene, tenemos, tienen | Preterite: tuve, tuviste, tuvo, tuvimos, tuvieron" },
      { en: "To go", es: "Ir", note: "Present: voy, vas, va, vamos, van | Preterite: fui, fuiste, fue, fuimos, fueron" },
      { en: "To do / make", es: "Hacer", note: "Present: hago/haces/hace/hacemos/hacen | Preterite: hice/hiciste/hizo/hicimos/hicieron" },
      { en: "Can / to be able to", es: "Poder", note: "Present: puedo/puedes/puede/podemos/pueden | Preterite: pude/pudiste/pudo/pudimos/pudieron" },
      { en: "To want", es: "Querer", note: "Present: quiero/quieres/quiere/queremos/quieren | Preterite: quise/quisiste/quiso/quisimos/quisieron" },
      { en: "To know (a fact)", es: "Saber", note: "Present: sé, sabes, sabe, sabemos, saben | Preterit: supe, supiste, supo, supimos, supisteis, supieron" },
      { en: "To see / watch", es: "Ver", note: "Present: veo/ves/ve/vemos/ven | Preterite: vi/viste/vio/vimos/vieron" },
      { en: "To say / tell", es: "Decir", note: "Present: digo/dices/dice/decimos/dicen | Preterite: dije/dijiste/dijo/dijimos/dijeron" },
      { en: "To come", es: "Venir", note: "Present: vengo/vienes/viene/venimos/vienen | Preterite: vine/viniste/vino/vinimos/vinieron" },
      { en: "To put / place", es: "Poner", note: "Present: pongo/pones/pone/ponemos/ponen | Preterite: puse, pusiste, puso, pusimos, pusisteis, pusieron" },
      { en: "To leave / go out", es: "Salir", note: "Present: salgo/sales/sale/salimos/salen" },
      { en: "To bring", es: "Traer", note: "Present: traigo/traes/trae/traemos/traen | Preterite: traje, trajiste, trajo, trajimos, trajisteis, trajeron" },
      { en: "To give", es: "Dar", note: "Present: doy/das/da/damos/dan | Preterite: di/diste/dio/dimos/dieron" },
    ],
  },
  {
    name: "VERBS - common (pt. 1)",
    terms: [
      { en: "To eat", es: "Comer" },
      { en: "To drink", es: "Tomar" },
      { en: "To sleep", es: "Dormir", note: "present stem-change o→ue: duermo/duermes/duerme/dormimos/duermen | preterite stem-change in 3rd person: dormí/dormiste/durmió/dormimos/durmieron" },
      { en: "To walk", es: "Caminar" },
      { en: "To run", es: "Correr" },
      { en: "To work", es: "Trabajar" },
      { en: "To play", es: "Jugar", note: "present stem-change u→ue: juego/juegas/juega/jugamos/juegan | preterite yo spelling change: jugué/jugaste/jugó/jugamos/jugaron" },
      { en: "To study", es: "Estudiar" },
      { en: "To travel", es: "Viajar" },
      { en: "To leave", es: "Salir", note: "present irregular yo: salgo/sales/sale/salimos/salen" },
      { en: "To arrive", es: "Llegar" },
      { en: "To buy", es: "Comprar" },
      { en: "To sell", es: "Vender" },
      { en: "To listen", es: "Escuchar" },
      { en: "To speak", es: "Hablar" },
      { en: "To watch", es: "Ver", note: "present irregular yo: veo/ves/ve/vemos/ven | preterite fully irregular: vi/viste/vio/vimos/vieron" },
      { en: "To read", es: "Leer", note: "preterite spelling change in 3rd person: leí/leíste/leyó/leímos/leyeron" },
      { en: "To write", es: "Escribir" },
      { en: "To think", es: "Pensar", note: "present stem-change e→ie: pienso/piensas/piensa/pensamos/piensan" },
      { en: "To know (a fact)", es: "Saber", note: "present irregular yo: sé/sabes/sabe/sabemos/saben | preterite fully irregular: supe/supiste/supo/supimos/supieron" },
    ],
  },
  {
    name: "VERBS - common (pt. 2)",
    terms: [
      { en: "To need", es: "Necesitar" },
      { en: "To have to / must", es: "Tener que" },
      { en: "To move", es: "Moverse" },
      { en: "To change", es: "Cambiar" },
      { en: "To send", es: "Enviar" },
      { en: "To receive", es: "Recibir" },
      { en: "To try", es: "Intentar" },
      { en: "To stop", es: "Parar" },
      { en: "To return", es: "Volver", note: "stem-change o→ue: vuelvo/vuelves/vuelve/volvemos/vuelven" },
      { en: "To put on / wear", es: "Ponerse" },
      { en: "To take off", es: "Quitarse" },
      { en: "To wake up", es: "Despertarse" },
      { en: "To get dressed", es: "Vestirse" },
      { en: "To feel", es: "Sentir", note: "stem-change e→ie: siento/sientes/siente/sentimos/sienten" },
      { en: "To want", es: "Querer", note: "stem-change e→ie: quiero/quieres/quiere/queremos/quieren" },
      { en: "To forget", es: "Olvidar" },
      { en: "To remember", es: "Recordar", note: "stem-change o→ue: recuerdo/recuerdas/recuerda/recordamos/recuerdan" },
      { en: "To understand", es: "Entender", note: "stem-change e→ie: entiendo/entiendes/entiende/entendemos/entienden" },
      { en: "To explain", es: "Explicar" },
      { en: "To help", es: "Ayudar" },
      { en: "To ask", es: "Preguntar" },
      { en: "To answer", es: "Contestar" },
      { en: "To call", es: "Llamar" },
      { en: "To wait", es: "Esperar" },
      { en: "To find", es: "Encontrar", note: "stem-change o→ue: encuentro/encuentras/encuentra/encontramos/encuentran" },
      { en: "To lose", es: "Perder", note: "stem-change e→ie: pierdo/pierdes/pierde/perdemos/pierden" },
      { en: "To win", es: "Ganar" },
      { en: "To pay", es: "Pagar" },
      { en: "To open", es: "Abrir" },
      { en: "To close", es: "Cerrar", note: "stem-change e→ie: cierro/cierras/cierra/cerramos/cierran" },
      { en: "To start", es: "Empezar", note: "stem-change e→ie: empiezo/empiezas/empieza/empezamos/empiezan" },
      { en: "To continue", es: "Seguir", note: "stem-change e→i: sigo/sigues/sigue/seguimos/siguen" },
      { en: "To finish", es: "Terminar" },
    ],
  },
  {
    name: "VERBS - common (pt. 3)",
    terms: [
      { en: "To think", es: "Pensar", note: "irregular: pienso/piensas/piensa/pensamos/piensan" },
      { en: "To know (a fact)", es: "Saber", note: "irregular: sé/sabes/sabe/sabemos/saben" },
      { en: "To know (a person/place)", es: "Conocer", note: "irregular: conozco/conoces/conoce/conocemos/conocen" },
      { en: "To learn", es: "Aprender" },
      { en: "To study", es: "Estudiar" },
      { en: "To remember", es: "Recordar", note: "irregular: recuerdo/recuerdas/recuerda/recordamos/recuerdan" },
      { en: "To forget", es: "Olvidar" },
      { en: "To understand", es: "Entender", note: "irregular: entiendo/entiendes/entiende/entendemos/entienden" },
      { en: "To imagine", es: "Imaginar" },
      { en: "To believe", es: "Creer" },
      { en: "To doubt", es: "Dudar" },
      { en: "To decide", es: "Decidir" },
      { en: "To choose", es: "Elegir", note: "irregular: elijo/eliges/elige/elegimos/eligen" },
      { en: "To plan", es: "Planear" },
      { en: "To focus", es: "Enfocarse" },
      { en: "To practice", es: "Practicar" },
      { en: "To improve", es: "Mejorar" },
    ],
  },
  {
    name: "VERBS - physical actions",
    terms: [
      { en: "To sit", es: "Sentarse", note: "present stem-change e→ie: me siento/te sientas/se sienta/nos sentamos/se sientan" },
      { en: "To stand up", es: "Levantarse" },
      { en: "To walk", es: "Caminar" },
      { en: "To run", es: "Correr" },
      { en: "To jump", es: "Saltar" },
      { en: "To throw", es: "Lanzar", note: "preterite yo spelling change: lancé/lanzaste/lanzó/lanzamos/lanzaron" },
      { en: "To kick", es: "Patear" },
      { en: "To punch", es: "Golpear" },
      { en: "To slap", es: "Abofetear" },
      { en: "To dance", es: "Bailar" },
      { en: "To swim", es: "Nadar" },
      { en: "To climb", es: "Escalar" },
      { en: "To fall", es: "Caerse", note: "present irregular yo: me caigo/te caes/se cae/nos caemos/se caen | preterite: me caí/te caíste/se cayó/nos caímos/se cayeron" },
      { en: "To push", es: "Empujar" },
      { en: "To pull", es: "Jalar" },
      { en: "To lift", es: "Levantar" },
      { en: "To carry", es: "Cargar", note: "preterite yo spelling change: cargué/cargaste/cargó/cargamos/cargaron" },
      { en: "To stretch", es: "Estirarse" },
      { en: "To crawl", es: "Gatear" },
    ],
  },

  // ---------------- ADJECTIVES ----------------
  {
    name: "ADJECTIVES - common (pt. 1)",
    terms: [
      { en: "Big", es: "Grande" },
      { en: "Small", es: "Pequeño / Pequeña" },
      { en: "Tall", es: "Alto / Alta" },
      { en: "Short", es: "Bajo / Baja" },
      { en: "Fast", es: "Rápido / Rápida" },
      { en: "Slow", es: "Lento / Lenta" },
      { en: "Strong", es: "Fuerte" },
      { en: "Weak", es: "Débil" },
      { en: "Beautiful", es: "Hermoso / Hermosa" },
      { en: "Ugly", es: "Feo / Fea" },
      { en: "Young", es: "Joven" },
      { en: "Old", es: "Viejo / Vieja" },
      { en: "Rich", es: "Rico / Rica" },
      { en: "Poor", es: "Pobre" },
      { en: "Easy", es: "Fácil" },
      { en: "Difficult", es: "Difícil" },
      { en: "Interesting", es: "Interesante" },
      { en: "Boring", es: "Aburrido / Aburrida" },
      { en: "Funny", es: "Gracioso / Graciosa" },
      { en: "Serious", es: "Serio / Seria" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 2) - colors",
    terms: [
      { en: "Red", es: "Rojo" },
      { en: "Blue", es: "Azul" },
      { en: "Green", es: "Verde" },
      { en: "Yellow", es: "Amarillo" },
      { en: "Orange", es: "Anaranjado" },
      { en: "Purple", es: "Morado" },
      { en: "Pink", es: "Rosado" },
      { en: "White", es: "Blanco" },
      { en: "Gray", es: "Gris" },
      { en: "Brown", es: "Café" },
      { en: "Dark", es: "Oscuro" },
      { en: "Light", es: "Claro" },
      { en: "Black", es: "Negro" },
      { en: "Gold", es: "Oro" },
      { en: "Silver", es: "Plata" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 3) - feelings",
    terms: [
      { en: "Happy", es: "Feliz" },
      { en: "Sad", es: "Triste" },
      { en: "Depressed", es: "Deprimido / Deprimida" },
      { en: "Angry", es: "Enojado / Enojada" },
      { en: "Confused", es: "Confundido / Confundida" },
      { en: "Tired", es: "Cansado / Cansada" },
      { en: "Alert", es: "Alerta" },
      { en: "Bored", es: "Aburrido / Aburrida" },
      { en: "Afraid", es: "Asustado / Asustada" },
      { en: "Stressed", es: "Estresado / Estresada" },
      { en: "Confident", es: "Seguro / Segura (de sí mismo)" },
      { en: "Anxious", es: "Ansioso / Ansiosa" },
      { en: "Nervous", es: "Nervioso / Nerviosa" },
      { en: "Curious", es: "Curioso / Curiosa" },
      { en: "Jealous", es: "Celoso / Celosa" },
      { en: "Excited", es: "Emocionado / Emocionada" },
      { en: "Calm", es: "Tranquilo / Tranquila" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 4)",
    terms: [
      { en: "Full", es: "Lleno / Llena" },
      { en: "Empty", es: "Vacío / Vacía" },
      { en: "Clean", es: "Limpio / Limpia" },
      { en: "Dirty", es: "Sucio / Sucia" },
      { en: "Hot", es: "Caliente" },
      { en: "Cold", es: "Frío / Fría" },
      { en: "New", es: "Nuevo / Nueva" },
      { en: "Same", es: "Mismo / Misma" },
      { en: "Different", es: "Diferente" },
      { en: "Open", es: "Abierto / Abierta" },
      { en: "Closed", es: "Cerrado / Cerrada" },
      { en: "Free (available)", es: "Libre" },
      { en: "Busy", es: "Ocupado / Ocupada" },
      { en: "Near", es: "Cerca" },
      { en: "Far", es: "Lejos" },
      { en: "Right", es: "Correcto / Correcta" },
      { en: "Wrong", es: "Incorrecto / Incorrecta" },
      { en: "Ready", es: "Listo / Lista" },
      { en: "Loud", es: "Ruidoso / Ruidosa" },
      { en: "Quiet", es: "Silencioso / Silenciosa" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 5)",
    terms: [
      { en: "Healthy", es: "Sano / Sana" },
      { en: "Sick", es: "Enfermo / Enferma" },
      { en: "Drunk", es: "Borracho / Borracha" },
      { en: "Sober", es: "Sobrio / Sobria" },
      { en: "Hungry", es: "Hambriento / Hambrienta" },
      { en: "Thirsty", es: "Sediento / Sedienta" },
      { en: "Sleepy", es: "Somnoliento / Somnolienta" },
      { en: "Alive", es: "Vivo / Viva" },
      { en: "Dead", es: "Muerto / Muerta" },
      { en: "Lost", es: "Perdido / Perdida" },
      { en: "Safe", es: "Seguro / Segura" },
      { en: "Dangerous", es: "Peligroso / Peligrosa" },
      { en: "Alone", es: "Solo / Sola" },
      { en: "Together", es: "Juntos / Juntas" },
      { en: "Possible", es: "Posible" },
      { en: "Impossible", es: "Imposible" },
      { en: "Necessary", es: "Necesario / Necesaria" },
      { en: "Important", es: "Importante" },
      { en: "Normal", es: "Normal" },
      { en: "Strange", es: "Extraño / Extraña" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 6)",
    terms: [
      { en: "Comfortable", es: "Cómodo / Cómoda" },
      { en: "Uncomfortable", es: "Incómodo / Incómoda" },
      { en: "Expensive", es: "Caro / Cara" },
      { en: "Cheap", es: "Barato / Barata" },
      { en: "Heavy", es: "Pesado / Pesada" },
      { en: "Light (weight)", es: "Ligero / Ligera" },
      { en: "Delicious", es: "Delicioso / Deliciosa" },
      { en: "Disgusting", es: "Asqueroso / Asquerosa" },
      { en: "Spicy", es: "Picante" },
      { en: "Sweet", es: "Dulce" },
      { en: "Sour", es: "Agrio / Agria" },
      { en: "Salty", es: "Salado / Salada" },
      { en: "Loud (person/personality)", es: "Escandaloso / Escandalosa" },
      { en: "Friendly", es: "Amigable" },
      { en: "Kind", es: "Amable" },
      { en: "Rude", es: "Grosero / Grosera" },
      { en: "Polite", es: "Educado / Educada" },
      { en: "Honest", es: "Honesto / Honesta" },
      { en: "Patient", es: "Paciente" },
      { en: "Impatient", es: "Impaciente" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 7)",
    terms: [
      { en: "Skinny", es: "Delgado / Delgada" },
      { en: "Fat", es: "Gordo / Gorda" },
      { en: "Muscular", es: "Musculoso / Musculosa" },
      { en: "Bald", es: "Calvo / Calva" },
      { en: "Handsome", es: "Guapo / Guapa" },
      { en: "Pretty", es: "Bonito / Bonita" },
      { en: "Cute", es: "Lindo / Linda" },
      { en: "Shy", es: "Tímido / Tímida" },
      { en: "Outgoing", es: "Extrovertido / Extrovertida" },
      { en: "Lazy", es: "Perezoso / Perezosa" },
      { en: "Hardworking", es: "Trabajador / Trabajadora" },
      { en: "Generous", es: "Generoso / Generosa" },
      { en: "Selfish", es: "Egoísta" },
      { en: "Smart", es: "Inteligente" },
      { en: "Stupid", es: "Tonto / Tonta" },
      { en: "Creative", es: "Creativo / Creativa" },
      { en: "Talented", es: "Talentoso / Talentosa" },
      { en: "Responsible", es: "Responsable" },
      { en: "Irresponsible", es: "Irresponsable" },
      { en: "Mature", es: "Maduro / Madura" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 8)",
    terms: [
      { en: "Enough", es: "Suficiente" },
      { en: "More", es: "Más" },
      { en: "Less", es: "Menos" },
      { en: "A lot / Much", es: "Mucho / Mucha" },
      { en: "A little", es: "Poco / Poca" },
      { en: "All / Every", es: "Todo / Toda" },
      { en: "Better", es: "Mejor" },
      { en: "Worse", es: "Peor" },
      { en: "First", es: "Primero / Primera" },
      { en: "Last", es: "Último / Última" },
      { en: "Next", es: "Próximo / Próxima" },
      { en: "Whole / Entire", es: "Entero / Entera" },
      { en: "Wide", es: "Ancho / Ancha" },
      { en: "Narrow", es: "Estrecho / Estrecha" },
      { en: "Deep", es: "Profundo / Profunda" },
      { en: "Shallow", es: "Poco profundo" },
      { en: "Sharp", es: "Afilado / Afilada" },
      { en: "Dull (not sharp)", es: "Desafilado / Desafilada" },
      { en: "Round", es: "Redondo / Redonda" },
      { en: "Square", es: "Cuadrado / Cuadrada" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 9)",
    terms: [
      { en: "Free (no cost)", es: "Gratis" },
      { en: "Public", es: "Público / Pública" },
      { en: "Private", es: "Privado / Privada" },
      { en: "Common", es: "Común" },
      { en: "Rare", es: "Raro / Rara" },
      { en: "Modern", es: "Moderno / Moderna" },
      { en: "Ancient", es: "Antiguo / Antigua" },
      { en: "Local", es: "Local" },
      { en: "Foreign", es: "Extranjero / Extranjera" },
      { en: "National", es: "Nacional" },
      { en: "International", es: "Internacional" },
      { en: "Legal", es: "Legal" },
      { en: "Illegal", es: "Ilegal" },
      { en: "Real", es: "Real" },
      { en: "Fake", es: "Falso / Falsa" },
      { en: "Complete", es: "Completo / Completa" },
      { en: "Incomplete", es: "Incompleto / Incompleta" },
      { en: "Available", es: "Disponible" },
      { en: "Unavailable", es: "No disponible" },
      { en: "Popular", es: "Popular" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 10)",
    terms: [
      { en: "Single (relationship status)", es: "Soltero / Soltera" },
      { en: "Married", es: "Casado / Casada" },
      { en: "Divorced", es: "Divorciado / Divorciada" },
      { en: "Pregnant", es: "Embarazada" },
      { en: "Adult", es: "Adulto / Adulta" },
      { en: "Elderly", es: "Anciano / Anciana" },
      { en: "Blind", es: "Ciego / Ciega" },
      { en: "Deaf", es: "Sordo / Sorda" },
      { en: "Injured", es: "Herido / Herida" },
      { en: "Broken", es: "Roto / Rota" },
      { en: "Fixed", es: "Arreglado / Arreglada" },
      { en: "Wet", es: "Mojado / Mojada" },
      { en: "Dry", es: "Seco / Seca" },
      { en: "Cunning", es: "Astuto / Astuta" },
      { en: "Wise", es: "Sabio / Sabia" },
      { en: "Brave", es: "Valiente" },
      { en: "Cowardly", es: "Cobarde" },
      { en: "Cruel", es: "Cruel" },
      { en: "Gentle", es: "Suave" },
      { en: "Loyal", es: "Leal" },
    ],
  },

  // ---------------- MISC ----------------
  {
    name: "MISC - time words",
    terms: [
      { en: "Monday", es: "lunes" },
      { en: "Tuesday", es: "martes" },
      { en: "Wednesday", es: "miércoles" },
      { en: "Thursday", es: "jueves" },
      { en: "Friday", es: "viernes" },
      { en: "Saturday", es: "sábado" },
      { en: "Sunday", es: "domingo" },
      { en: "January", es: "enero" },
      { en: "February", es: "febrero" },
      { en: "March", es: "marzo" },
      { en: "April", es: "abril" },
      { en: "May", es: "mayo" },
      { en: "June", es: "junio" },
      { en: "July", es: "julio" },
      { en: "August", es: "agosto" },
      { en: "September", es: "septiembre" },
      { en: "October", es: "octubre" },
      { en: "November", es: "noviembre" },
      { en: "December", es: "diciembre" },
      { en: "Minute", es: "el minuto" },
      { en: "Hour", es: "la hora" },
      { en: "Day", es: "El día" },
      { en: "Week", es: "La semana" },
      { en: "Month", es: "el mes" },
      { en: "Year", es: "el año" },
      { en: "Yesterday", es: "ayer" },
      { en: "Today", es: "hoy" },
      { en: "Tomorrow", es: "mañana" },
      { en: "Last week", es: "la semana pasada" },
      { en: "This week", es: "esta semana" },
      { en: "Next week", es: "la semana que viene" },
      { en: "Last year", es: "el año pasado" },
      { en: "This year", es: "este año" },
      { en: "Next year", es: "el año que viene" },
      { en: "Morning", es: "la mañana" },
      { en: "afternoon", es: "la tarde" },
      { en: "Night", es: "la noche" },
      { en: "Now", es: "ahora" },
      { en: "Right now", es: "ahora mismo" },
      { en: "Soon", es: "pronto" },
      { en: "Later", es: "más tarde" },
      { en: "Always", es: "siempre" },
      { en: "Never", es: "nunca" },
      { en: "Sometimes", es: "a veces" },
      { en: "Already", es: "ya" },
      { en: "Still", es: "todavía" },
      { en: "Early", es: "temprano" },
      { en: "Late", es: "tarde" },
      { en: "Before", es: "antes" },
      { en: "During", es: "durante" },
      { en: "After", es: "después" },
      { en: "While", es: "mientras" },
      { en: "When", es: "cuando" },
      { en: "Since", es: "desde" },
      { en: "Until", es: "hasta" },
      { en: "Again", es: "otra vez" },
      { en: "Finally", es: "por fin" },
      { en: "Second", es: "El segundo" },
      { en: "Last night", es: "anoche" },
      { en: "Tonight", es: "esta noche" },
      { en: "Tomorrow night", es: "mañana por la noche" },
      { en: "Yesterday morning", es: "ayer por la mañana" },
      { en: "This morning", es: "esta mañana" },
      { en: "Tomorrow morning", es: "mañana por la mañana" },
      { en: "Yesterday afternoon", es: "ayer por la tarde" },
      { en: "This afternoon", es: "esta tarde" },
      { en: "Tomorrow afternoon", es: "mañana por la tarde" },
      { en: "Every", es: "cada" },
      { en: "(to do something) in the morning", es: "por la mañana" },
      { en: "(to do something) in the afternoon", es: "por la tarde" },
      { en: "(to do something) at night", es: "por la noche" },
      { en: "(some time, like clock) in the morning", es: "de la mañana" },
      { en: "(some time, like clock) in the afternoon", es: "de la tarde" },
      { en: "(some time, like clock) at night", es: "de la noche" },
      { en: "All morning", es: "toda la mañana" },
      { en: "All afternoon", es: "toda la tarde" },
      { en: "All night", es: "toda la noche" },
      { en: "All day", es: "todo el día" },
    ],
  },
  {
    name: "MISC - gustar-type verbs & pronouns",
    terms: [
      { en: "To be pleasing to (to like)", es: "Gustar" },
      { en: "To be enchanting to (to love)", es: "Encantar" },
      { en: "To interest", es: "Interesar" },
      { en: "To cause pain to (to hurt)", es: "Doler" },
      { en: "My / his / her / your (formal) / our", es: "mi(s) / su(s) / nuestro(s) / nuestra(s)" },
      { en: "Indirect object pronouns", es: "me / te / le / nos / les" },
    ],
  },
  {
    name: "MISC - numbers",
    terms: [
      { en: "One", es: "uno" },
      { en: "Two", es: "dos" },
      { en: "Three", es: "tres" },
      { en: "Four", es: "cuatro" },
      { en: "Five", es: "cinco" },
      { en: "Six", es: "seis" },
      { en: "Seven", es: "siete" },
      { en: "Eight", es: "ocho" },
      { en: "Nine", es: "nueve" },
      { en: "Ten", es: "diez" },
      { en: "Eleven", es: "once" },
      { en: "Twelve", es: "doce" },
      { en: "Thirteen", es: "trece" },
      { en: "Fourteen", es: "catorce" },
      { en: "Fifteen", es: "quince" },
      { en: "Sixteen", es: "dieciséis" },
      { en: "Seventeen", es: "diecisiete" },
      { en: "Eighteen", es: "dieciocho" },
      { en: "Nineteen", es: "diecinueve" },
      { en: "Twenty", es: "veinte" },
      { en: "Twenty-one", es: "veintiuno" },
      { en: "Thirty", es: "treinta" },
      { en: "Forty", es: "cuarenta" },
      { en: "Fifty", es: "cincuenta" },
      { en: "Sixty", es: "sesenta" },
      { en: "Seventy", es: "setenta" },
      { en: "Eighty", es: "ochenta" },
      { en: "Ninety", es: "noventa" },
      { en: "One hundred", es: "cien" },
      { en: "One hundred one", es: "ciento uno" },
      { en: "Two hundred", es: "doscientos" },
      { en: "Three hundred", es: "trescientos" },
      { en: "Four hundred", es: "cuatrocientos" },
      { en: "Five hundred", es: "quinientos" },
      { en: "Six hundred", es: "seiscientos" },
      { en: "Seven hundred", es: "setecientos" },
      { en: "Eight hundred", es: "ochocientos" },
      { en: "Nine hundred", es: "novecientos" },
      { en: "One thousand", es: "mil" },
      { en: "Two thousand", es: "dos mil" },
    ],
  },
  {
    name: "MISC - question words",
    terms: [
      { en: "What", es: "Qué" },
      { en: "Who", es: "Quién" },
      { en: "Where", es: "Dónde" },
      { en: "When", es: "Cuándo" },
      { en: "Why", es: "Por qué" },
      { en: "How", es: "Cómo" },
      { en: "How much", es: "Cuánto" },
      { en: "How many", es: "Cuántos" },
      { en: "Which", es: "Cuál" },
      { en: "Where to", es: "Adónde" },
    ],
  },
  {
    name: "MISC - common questions",
    terms: [
      { en: "What is your name?", es: "¿Cómo te llamas? / ¿Cuál es tu nombre?" },
      { en: "How are you?", es: "¿Cómo estás? / ¿Qué tal?" },
      { en: "Where are you from?", es: "¿De dónde eres?" },
      { en: "Where do you live?", es: "¿Dónde vives?" },
      { en: "How old are you?", es: "¿Cuántos años tienes?" },
      { en: "What time is it?", es: "¿Qué hora es?" },
      { en: "What do you want?", es: "¿Qué quieres?" },
      { en: "Where is the bathroom?", es: "¿Dónde está el baño?" },
      { en: "How much does it cost?", es: "¿Cuánto cuesta? / ¿Cuánto es?" },
      { en: "What are you doing?", es: "¿Qué haces? / ¿Qué estás haciendo?" },
      { en: "Do you speak English?", es: "¿Hablas inglés?" },
      { en: "Can you help me?", es: "¿Puedes ayudarme? / ¿Me puedes ayudar?" },
      { en: "What does it mean?", es: "¿Qué significa?" },
      { en: "Where are we going?", es: "¿Adónde vamos?" },
      { en: "Who is he?", es: "¿Quién es él?" },
      { en: "Why not?", es: "¿Por qué no?" },
      { en: "When do we leave?", es: "¿Cuándo salimos?" },
      { en: "Which one do you want?", es: "¿Cuál quieres?" },
      { en: "What happened?", es: "¿Qué pasó?" },
      { en: "Do you have the money?", es: "¿Tienes el dinero?" },
      { en: "How many people are there?", es: "¿Cuántas personas hay?" },
      { en: "Are you ready?", es: "¿Estás listo? / ¿Estás lista?" },
      { en: "Do you understand?", es: "¿Entiendes? / ¿Comprendes?" },
      { en: "Where is the hotel?", es: "¿Dónde está el hotel?" },
      { en: "What is this?", es: "¿Qué es esto?" },
    ],
  },
  {
    name: "MISC - connecting words (pt. 1)",
    terms: [
      { en: "But", es: "Pero" },
      { en: "Although", es: "Aunque" },
      { en: "Because", es: "Porque" },
      { en: "So / Therefore", es: "Entonces" },
      { en: "Also", es: "También" },
      { en: "Neither / Not either", es: "Tampoco" },
      { en: "And", es: "Y" },
      { en: "Or", es: "O" },
      { en: "If", es: "Si" },
      { en: "That", es: "Que" },
      { en: "So that", es: "Para que" },
      { en: "Without", es: "Sin" },
      { en: "With", es: "Con" },
      { en: "Against", es: "Contra" },
      { en: "Instead of", es: "En vez de" },
      { en: "As soon as", es: "En cuanto" },
      { en: "As long as", es: "Mientras que" },
      { en: "Even though", es: "Aunque" },
      { en: "However", es: "Sin embargo" },
      { en: "In fact", es: "De hecho" },
      { en: "For example", es: "Por ejemplo" },
    ],
  },
  {
    name: "MISC - adverb rules",
    terms: [
      {
        en: "Adverbs describing actions",
        es: "Use masculine singular adjective form regardless of gender when it describes HOW an action is done",
        note: "e.g. La niña corre rápido (not rápida). El hombre habla claro.",
      },
      {
        en: "-mente adverbs",
        es: "Add -mente to the feminine adjective form (Spanish's -ly)",
        note: "rápida→rápidamente, lenta→lentamente, tranquila→tranquilamente. Both forms are correct; the short form is more casual.",
      },
    ],
  },
];
