// Default seed data — loaded only on first run; after that, sets live in localStorage.
const DEFAULT_SETS = [
  // ---------------- NOUNS ----------------
  {
    name: "NOUNS - common (pt. 1) - people & family",
    terms: [
      { en: "The man", es: "el hombre" },
      { en: "The woman", es: "la mujer" },
      { en: "The boy", es: "el niño" },
      { en: "The girl", es: "la niña" },
      { en: "The friend", es: "el amigo / la amiga" },
      { en: "The family", es: "la familia" },
      { en: "The mother", es: "la madre" },
      { en: "The father", es: "el padre" },
      { en: "The parents", es: "los padres" },
      { en: "The brother", es: "el hermano" },
      { en: "The sister", es: "la hermana" },
      { en: "The half brother", es: "el medio hermano" },
      { en: "The half sister", es: "la media hermana" },
      { en: "The son", es: "el hijo" },
      { en: "The daughter", es: "la hija" },
      { en: "The child", es: "el niño / la niña" },
      { en: "The boyfriend", es: "el novio" },
      { en: "The girlfriend", es: "la novia" },
      { en: "The husband", es: "el marido" },
      { en: "The wife", es: "la esposa" },
      { en: "The grandmother", es: "la abuela" },
      { en: "The grandfather", es: "el abuelo" },
      { en: "The granddaughter", es: "la nieta" },
      { en: "The grandson", es: "el nieto" },
      { en: "The aunt", es: "la tía" },
      { en: "The uncle", es: "el tío" },
      { en: "The cousin", es: "el primo / la prima" },
    ],
  },
  {
    name: "NOUNS - common (pt. 2) - places",
    terms: [
      { en: "House", es: "La casa" },
      { en: "Apartment", es: "El apartamento" },
      { en: "Hotel", es: "El hotel" },
      { en: "Restaurant", es: "El restaurante" },
      { en: "Store", es: "La tienda" },
      { en: "Gym", es: "El gimnasio" },
      { en: "Beach", es: "La playa" },
      { en: "Park", es: "El parque" },
      { en: "Airport", es: "El aeropuerto" },
      { en: "Village", es: "El pueblo" },
      { en: "City", es: "La ciudad" },
      { en: "State", es: "El estado" },
      { en: "Country", es: "El país" },
      { en: "World", es: "El mundo" },
      { en: "School", es: "La escuela" },
      { en: "University", es: "La universidad" },
      { en: "Office", es: "La oficina" },
    ],
  },
  {
    name: "NOUNS - common (pt. 3) - body parts",
    terms: [
      { en: "The head", es: "la cabeza" },
      { en: "The face", es: "la cara" },
      { en: "The eye", es: "el ojo" },
      { en: "The eyes", es: "los ojos" },
      { en: "The nose", es: "la nariz" },
      { en: "The mouth", es: "la boca" },
      { en: "The ear", es: "la oreja" },
      { en: "The hair", es: "el pelo" },
      { en: "The neck", es: "el cuello" },
      { en: "The shoulder", es: "el hombro" },
      { en: "The arm", es: "el brazo" },
      { en: "The hand", es: "la mano" },
      { en: "The leg", es: "la pierna" },
      { en: "The foot", es: "el pie" },
      { en: "The back", es: "la espalda" },
      { en: "The vagina", es: "la vagina" },
      { en: "The breasts", es: "los senos" },
      { en: "The penis", es: "el pene" },
      { en: "The testicles", es: "los testículos" },
      { en: "The butt", es: "el trasero" },
      { en: "The elbow", es: "el codo" },
      { en: "The lips", es: "los labios" },
      { en: "The teeth", es: "los dientes" },
      { en: "The tongue", es: "la lengua" },
      { en: "The tattoo", es: "el tatuaje" },
    ],
  },
  {
    name: "NOUNS - common (pt. 4)",
    terms: [
      { en: "The food", es: "La comida" },
      { en: "The water", es: "El agua" },
      { en: "The coffee", es: "El café" },
      { en: "The beer", es: "La cerveza" },
      { en: "The wine", es: "El vino" },
      { en: "The money", es: "El dinero" },
      { en: "The phone", es: "El teléfono" },
      { en: "The car", es: "El carro" },
      { en: "The bus", es: "El autobús" },
      { en: "The street", es: "La calle" },
      { en: "The door", es: "La puerta" },
      { en: "The window", es: "La ventana" },
      { en: "The table", es: "La mesa" },
      { en: "The chair", es: "La silla" },
      { en: "The bed", es: "La cama" },
      { en: "The bathroom", es: "El baño" },
      { en: "The kitchen", es: "La cocina" },
      { en: "The room", es: "La habitación" },
      { en: "The bag", es: "La bolsa" },
      { en: "The key", es: "La llave" },
    ],
  },
  {
    name: "NOUNS - common (pt. 5)",
    terms: [
      { en: "The clothes", es: "La ropa" },
      { en: "The shirt", es: "La camisa" },
      { en: "The pants", es: "Los pantalones" },
      { en: "The shoes", es: "Los zapatos" },
      { en: "The jacket", es: "La chaqueta" },
      { en: "The hat", es: "El sombrero" },
      { en: "The sock", es: "El calcetín" },
      { en: "The dress", es: "El vestido" },
      { en: "The shorts", es: "Los pantalones cortos" },
      { en: "The underwear", es: "La ropa interior" },
      { en: "The backpack", es: "La mochila" },
      { en: "The suitcase", es: "La maleta" },
      { en: "The passport", es: "El pasaporte" },
      { en: "The ticket", es: "El boleto" },
      { en: "The map", es: "El mapa" },
      { en: "The market", es: "El mercado" },
      { en: "The hospital", es: "El hospital" },
      { en: "The pharmacy", es: "La farmacia" },
      { en: "The church", es: "La iglesia" },
      { en: "The mountain", es: "La montaña" },
      { en: "The river", es: "El río" },
    ],
  },
  {
    name: "NOUNS - common (pt. 6)",
    terms: [
      { en: "The breakfast", es: "El desayuno" },
      { en: "The lunch", es: "El almuerzo" },
      { en: "The dinner", es: "La cena" },
      { en: "The meat", es: "La carne" },
      { en: "The chicken", es: "El pollo" },
      { en: "The fish", es: "El pescado" },
      { en: "The rice", es: "El arroz" },
      { en: "The bread", es: "El pan" },
      { en: "The egg", es: "El huevo" },
      { en: "The cheese", es: "El queso" },
      { en: "The fruit", es: "La fruta" },
      { en: "The vegetable", es: "La verdura" },
      { en: "The soup", es: "La sopa" },
      { en: "The salad", es: "La ensalada" },
      { en: "The dessert", es: "El postre" },
      { en: "The juice", es: "El jugo" },
      { en: "The milk", es: "La leche" },
      { en: "The ice", es: "El hielo" },
      { en: "The bill / check", es: "La cuenta" },
      { en: "The tip", es: "La propina" },
    ],
  },
  {
    name: "NOUNS - common (pt. 7) - more people",
    terms: [
      { en: "The doctor", es: "El doctor / La doctora" },
      { en: "The teacher", es: "El profesor / La profesora" },
      { en: "The waiter", es: "El mesero / La mesera" },
      { en: "The police officer", es: "El policía / La mujer policía" },
      { en: "The driver", es: "El conductor / La conductora" },
      { en: "The cook / chef", es: "El cocinero / La cocinera" },
      { en: "The engineer", es: "El ingeniero / La ingeniera" },
      { en: "The lawyer", es: "El abogado / La abogada" },
      { en: "The nurse", es: "El enfermero / La enfermera" },
      { en: "The student", es: "El estudiante / La estudiante" },
      { en: "The tourist", es: "El turista / La turista" },
      { en: "The stranger", es: "El desconocido / La desconocida" },
      { en: "The neighbor", es: "El vecino / La vecina" },
      { en: "The boss", es: "El jefe / La jefa" },
      { en: "The employee", es: "El empleado / La empleada" },
      { en: "The owner", es: "El dueño / La dueña" },
      { en: "The customer", es: "El cliente / La clienta" },
      { en: "The guide", es: "El guía / La guía" },
      { en: "The artist", es: "El artista / La artista" },
      { en: "The musician", es: "El músico / La música" },
    ],
  },
  {
    name: "NOUNS - common (pt. 8) - more places",
    terms: [
      { en: "The pool", es: "La piscina" },
      { en: "The lake", es: "El lago" },
      { en: "The ocean", es: "El océano" },
      { en: "The forest", es: "El bosque" },
      { en: "The desert", es: "El desierto" },
      { en: "The island", es: "La isla" },
      { en: "The bridge", es: "El puente" },
      { en: "The museum", es: "El museo" },
      { en: "The library", es: "La biblioteca" },
      { en: "The bank", es: "El banco" },
      { en: "The stadium", es: "El estadio" },
      { en: "The theater", es: "El teatro" },
      { en: "The cinema", es: "El cine" },
      { en: "The temple", es: "El templo" },
      { en: "The castle", es: "El castillo" },
      { en: "The volcano", es: "El volcán" },
      { en: "The waterfall", es: "La cascada" },
      { en: "The cave", es: "La cueva" },
      { en: "The border", es: "La frontera" },
      { en: "The neighborhood", es: "El barrio" },
    ],
  },
  {
    name: "NOUNS - common (pt. 9)",
    terms: [
      { en: "The computer", es: "La computadora" },
      { en: "The internet", es: "El internet" },
      { en: "The message", es: "El mensaje" },
      { en: "The password", es: "La contraseña" },
      { en: "The battery", es: "La batería" },
      { en: "The charger", es: "El cargador" },
      { en: "The weather", es: "El clima" },
      { en: "The sun", es: "El sol" },
      { en: "The rain", es: "La lluvia" },
      { en: "The wind", es: "El viento" },
      { en: "The cloud", es: "La nube" },
      { en: "The sky", es: "El cielo" },
      { en: "The star", es: "La estrella" },
      { en: "The moon", es: "La luna" },
      { en: "The towel", es: "La toalla" },
      { en: "The sunscreen", es: "El protector solar" },
      { en: "The glasses", es: "Las gafas" },
      { en: "The camera", es: "La cámara" },
      { en: "The picture", es: "La foto" },
      { en: "The video", es: "El video" },
    ],
  },
  {
    name: "NOUNS - common (pt. 10)",
    terms: [
      { en: "The problem", es: "El problema" },
      { en: "The idea", es: "La idea" },
      { en: "The plan", es: "El plan" },
      { en: "The reason", es: "La razón" },
      { en: "The truth", es: "La verdad" },
      { en: "The lie", es: "La mentira" },
      { en: "The secret", es: "El secreto" },
      { en: "The question", es: "La pregunta" },
      { en: "The answer", es: "La respuesta" },
      { en: "The list", es: "La lista" },
      { en: "The rule", es: "La regla" },
      { en: "The example", es: "El ejemplo" },
      { en: "The mistake", es: "El error" },
      { en: "The surprise", es: "La sorpresa" },
      { en: "The gift", es: "El regalo" },
      { en: "The party", es: "La fiesta" },
      { en: "The trip", es: "El viaje" },
      { en: "The itinerary", es: "El itinerario" },
      { en: "The luggage", es: "El equipaje" },
      { en: "The flight", es: "El vuelo" },
    ],
  },
  {
    name: "NOUNS - common (pt. 11)",
    terms: [
      { en: "The tree", es: "El árbol" },
      { en: "The flower", es: "La flor" },
      { en: "The grass", es: "La hierba" },
      { en: "The leaf", es: "La hoja" },
      { en: "The rock", es: "La piedra" },
      { en: "The sand", es: "La arena" },
      { en: "The fire", es: "El fuego" },
      { en: "The smoke", es: "El humo" },
      { en: "The earth", es: "La tierra" },
      { en: "The animal", es: "El animal" },
      { en: "The bird", es: "El pájaro" },
      { en: "The insect", es: "El insecto" },
      { en: "The snake", es: "La serpiente" },
      { en: "The spider", es: "La araña" },
      { en: "The life", es: "La vida" },
      { en: "The death", es: "La muerte" },
      { en: "The love", es: "El amor" },
      { en: "The hate", es: "El odio" },
      { en: "The peace", es: "La paz" },
      { en: "The war", es: "La guerra" },
      { en: "The freedom", es: "La libertad" },
    ],
  },
  {
    name: "NOUNS - common (pt. 12)",
    terms: [
      { en: "The season", es: "La estación" },
      { en: "Winter", es: "El invierno" },
      { en: "Spring", es: "La primavera" },
      { en: "Summer", es: "El verano" },
      { en: "Fall / Autumn", es: "El otoño" },
      { en: "The job", es: "El trabajo" },
      { en: "The company", es: "La empresa" },
      { en: "The meeting", es: "La reunión" },
      { en: "The project", es: "El proyecto" },
      { en: "The goal", es: "La meta" },
      { en: "The dream", es: "El sueño" },
      { en: "The memory", es: "El recuerdo" },
      { en: "The experience", es: "La experiencia" },
      { en: "The change", es: "El cambio" },
      { en: "The decision", es: "La decisión" },
      { en: "The opportunity", es: "La oportunidad" },
      { en: "The risk", es: "El riesgo" },
      { en: "The challenge", es: "El desafío" },
      { en: "The success", es: "El éxito" },
      { en: "The failure", es: "El fracaso" },
      { en: "The effort", es: "El esfuerzo" },
    ],
  },
  {
    name: "NOUNS - common (pt. 13)",
    terms: [
      { en: "The snow", es: "La nieve" },
      { en: "The storm", es: "La tormenta" },
      { en: "The building", es: "El edificio" },
      { en: "The truck", es: "El camión" },
      { en: "The driveway", es: "La entrada de coches" },
      { en: "The sidewalk", es: "La acera" },
      { en: "The highway", es: "La autopista" },
      { en: "The stoplight", es: "El semáforo" },
      { en: "The stop sign", es: "La señal de alto" },
      { en: "The intersection", es: "La intersección / El cruce" },
      { en: "The bicycle", es: "La bicicleta" },
      { en: "The pedestrian", es: "El peatón" },
      { en: "The train", es: "El tren" },
      { en: "The parking lot", es: "El estacionamiento" },
      { en: "The parking spot", es: "El lugar de estacionamiento" },
      { en: "The jail", es: "La cárcel" },
      { en: "The ATM", es: "El cajero automático" },
      { en: "The entrance", es: "La entrada" },
      { en: "The exit", es: "La salida" },
      { en: "The dollar", es: "El dólar" },
      { en: "The cent", es: "El centavo" },
    ],
  },
  {
    name: "NOUNS - common (pt. 14)",
    terms: [
      { en: "God", es: "Dios" },
      { en: "The person", es: "La persona" },
      { en: "The people", es: "La gente" },
      { en: "The place", es: "El lugar" },
      { en: "The thing", es: "La cosa" },
      { en: "The stuff", es: "Las cosas" },
      { en: "The baby", es: "El bebé" },
      { en: "The way", es: "La manera" },
      { en: "The thought", es: "El pensamiento" },
      { en: "The home", es: "El hogar" },
      { en: "The guy (casual)", es: "El chico" },
      { en: "The girl (casual)", es: "La chica" },
      { en: "The mind", es: "La mente" },
      { en: "The body", es: "El cuerpo" },
      { en: "The blood", es: "La sangre" },
      { en: "The start", es: "El comienzo" },
      { en: "The end", es: "El final" },
      { en: "The heart", es: "El corazón" },
      { en: "The part", es: "La parte" },
      { en: "The music", es: "La música" },
    ],
  },
  {
    name: "NOUNS - common (pt. 15)",
    terms: [
      { en: "The past", es: "El pasado" },
      { en: "The present", es: "El presente" },
      { en: "The future", es: "El futuro" },
      { en: "The sound", es: "El sonido" },
      { en: "The feeling", es: "El sentimiento" },
      { en: "The promise", es: "La promesa" },
      { en: "The air", es: "El aire" },
      { en: "The voice", es: "La voz" },
      { en: "The skin", es: "La piel" },
      { en: "The color", es: "El color" },
      { en: "The bottom", es: "El fondo" },
      { en: "The middle", es: "El medio" },
      { en: "The top", es: "La cima" },
      { en: "The left", es: "La izquierda" },
      { en: "The right", es: "La derecha" },
      { en: "The trouble", es: "El problema" },
      { en: "The fun", es: "La diversión" },
      { en: "The inside", es: "El interior" },
      { en: "The outside", es: "El exterior" },
      { en: "The ground", es: "El suelo" },
    ],
  },
  {
    name: "NOUNS - common (pt. 16)",
    terms: [
      { en: "The language", es: "El idioma" },
      { en: "The word", es: "La palabra" },
      { en: "The name", es: "El nombre" },
      { en: "The number", es: "El número" },
      { en: "The digit", es: "El dígito" },
      { en: "The movie", es: "La película" },
      { en: "The TV", es: "La televisión / El televisor" },
      { en: "The TV show", es: "El programa de televisión" },
      { en: "The documentary", es: "El documental" },
      { en: "The book", es: "El libro" },
      { en: "The class", es: "La clase" },
      { en: "The desk", es: "El escritorio" },
      { en: "The homework", es: "La tarea" },
      { en: "The pencil", es: "El lápiz" },
      { en: "The pen", es: "El bolígrafo" },
      { en: "The eraser", es: "El borrador" },
      { en: "The paper", es: "El papel" },
      { en: "The floor", es: "El suelo" },
      { en: "The floor (indoor ground / story of a building)", es: "El piso" },
      { en: "The wall", es: "La pared" },
      { en: "The ceiling", es: "El techo" },
    ],
  },
  {
    name: "NOUNS - common (pt. 17)",
    terms: [
      { en: "The dish", es: "El plato" },
      { en: "The cup", es: "La taza" },
      { en: "The bowl", es: "El tazón" },
      { en: "The plate", es: "El plato" },
      { en: "The bottle", es: "La botella" },
      { en: "The fork", es: "El tenedor" },
      { en: "The spoon", es: "La cuchara" },
      { en: "The knife", es: "El cuchillo" },
      { en: "The counter", es: "La encimera / El mostrador" },
      { en: "The sink", es: "El fregadero" },
      { en: "The garbage", es: "La basura" },
      { en: "The garbage can", es: "El bote de basura" },
      { en: "The refrigerator", es: "El refrigerador" },
      { en: "The freezer", es: "El congelador" },
      { en: "The oven", es: "El horno" },
      { en: "The stove", es: "La estufa" },
      { en: "The microwave", es: "El microondas" },
      { en: "The dishwasher", es: "El lavavajillas" },
      { en: "The napkin", es: "La servilleta" },
      { en: "The paper towel", es: "La toalla de papel" },
      { en: "The meal", es: "La comida" },
      { en: "The drink", es: "La bebida" },
    ],
  },
  {
    name: "NOUNS - common (pt. 18)",
    terms: [
      { en: "The bedroom", es: "El dormitorio" },
      { en: "The closet", es: "El armario" },
      { en: "The basement", es: "El sótano" },
      { en: "The roof", es: "El techo" },
      { en: "The stairs", es: "Las escaleras" },
      { en: "The carpet", es: "La alfombra" },
      { en: "The couch", es: "El sofá" },
      { en: "The mattress", es: "El colchón" },
      { en: "The blanket", es: "La manta" },
      { en: "The pillow", es: "La almohada" },
      { en: "The dresser", es: "La cómoda" },
      { en: "The drawer", es: "El cajón" },
      { en: "The curtain", es: "La cortina" },
      { en: "The washer", es: "La lavadora" },
      { en: "The dryer", es: "La secadora" },
      { en: "The laundry", es: "La ropa sucia" },
      { en: "The broom", es: "La escoba" },
      { en: "The vacuum", es: "La aspiradora" },
      { en: "The porch", es: "El porche" },
      { en: "The yard", es: "El patio" },
      { en: "The garden", es: "El jardín" },
      { en: "The fence", es: "La cerca" },
    ],
  },
  {
    name: "NOUNS - common (pt. 19)",
    terms: [
      { en: "The pocket", es: "El bolsillo" },
      { en: "The wallet", es: "La billetera" },
      { en: "The cash", es: "El efectivo" },
      { en: "The card", es: "La tarjeta" },
      { en: "The credit card", es: "La tarjeta de crédito", },
      { en: "The debit card", es: "La tarjeta de débito", },
      { en: "The ID", es: "El documento de identidad / El DNI", },
      { en: "The license", es: "La licencia" },
      { en: "The driver's license", es: "La licencia de conducir" },
      { en: "The purse", es: "La cartera" },
      { en: "The medicine", es: "La medicina" },
      { en: "The pill", es: "La pastilla" },
      { en: "The alcohol", es: "El alcohol" },
      { en: "The liquor", es: "El licor" },
      { en: "The nicotine", es: "La nicotina" },
      { en: "The cigar", es: "El puro" },
      { en: "The cigarette", es: "El cigarro" },
      { en: "The drug", es: "La droga" },
      { en: "The marijuana", es: "La marihuana" },
      { en: "The cocaine", es: "La cocaína" },
      { en: "The lighter", es: "El encendedor" },
    ],
  },
  {
    name: "NOUNS - common (pt. 20)",
    terms: [
      { en: "The doorknob", es: "La perilla" },
      { en: "The lock", es: "La cerradura" },
      { en: "The mirror", es: "El espejo" },
      { en: "The toothbrush", es: "El cepillo de dientes" },
      { en: "The toothpaste", es: "La pasta de dientes" },
      { en: "The floss", es: "El hilo dental" },
      { en: "The mouthwash", es: "El enjuague bucal" },
      { en: "The razor", es: "La rasuradora" },
      { en: "The shaving cream", es: "La crema de afeitar" },
      { en: "The toilet", es: "El inodoro" },
      { en: "The toilet paper", es: "El papel higiénico" },
      { en: "The rug", es: "La alfombra" },
      { en: "The shower", es: "La ducha" },
      { en: "The bath", es: "El baño" },
      { en: "The bathtub", es: "La bañera" },
      { en: "The soap", es: "El jabón" },
      { en: "The shampoo", es: "El champú" },
      { en: "The tissue", es: "El pañuelo de papel" },
      { en: "The makeup", es: "El maquillaje" },
      { en: "The candle", es: "La vela" },
      { en: "The fan", es: "El ventilador" }
    ]
  },
  {
    name: "NOUNS - common (pt. 21)",
    terms: [
      { en: "The laptop", es: "La laptop / La computadora portátil" },
      { en: "The headphones", es: "Los audífonos" },
      { en: "The speaker(s)", es: "El parlante / Los parlantes" },
      { en: "The keyboard", es: "El teclado" },
      { en: "The mouse", es: "El ratón" },
      { en: "The screen", es: "La pantalla" },
      { en: "The tablet", es: "La tableta" },
      { en: "The website", es: "El sitio web" },
      { en: "The app", es: "La aplicación / La app" },
      { en: "The email", es: "El correo electrónico / El email" },
      { en: "The user", es: "El usuario / La usuaria" },
      { en: "The username", es: "El nombre de usuario" },
      { en: "The account", es: "La cuenta" },
      { en: "The wi-fi", es: "El wifi" },
      { en: "The data", es: "Los datos" },
      { en: "The social media", es: "Las redes sociales" },
      { en: "The connection", es: "La conexión" },
      { en: "The translator", es: "El traductor" },
      { en: "The translation", es: "La traducción" },
      { en: "The accent", es: "El acento" },
    ],
  },

  // ---------------- VERBS ----------------
  {
    name: "VERBS - conjugations by tense",
    terms: [
      { en: "-ar verbs (preterite endings)", es: "-é, -aste, -ó, -amos, -aron" },
      { en: "-ar verbs (present endings)", es: "-o, -as, -a, -amos, -an" },
      { en: "-er verbs (preterite endings)", es: "-í, -iste, -ió, -imos, -ieron" },
      { en: "-er verbs (present endings)", es: "-o, -es, -e, -emos, -en" },
      { en: "-ir verbs (preterite endings)", es: "-í, -iste, -ió, -imos, -ieron" },
      { en: "-ir verbs (present endings)", es: "-o, -es, -e, -imos, -en" },
    ],
  },
  {
    name: "VERBS - irregular",
    terms: [
      { en: "To be (permanent)", es: "Ser", note: "Present: soy, eres, es, somos, son | Preterite: fui, fuiste, fue, fuimos, fueron" },
      { en: "To be (temporary)", es: "Estar", note: "Present: estoy, estás, está, estamos, están | Preterite: estuve, estuviste, estuvo, estuvimos, estuvieron" },
      { en: "To have", es: "Tener", note: "Present: tengo, tienes, tiene, tenemos, tienen | Preterite: tuve, tuviste, tuvo, tuvimos, tuvieron" },
      { en: "To go", es: "Ir", note: "Present: voy, vas, va, vamos, van | Preterite: fui, fuiste, fue, fuimos, fueron" },
      { en: "To do / make", es: "Hacer", note: "Present: hago/haces/hace/hacemos/hacen | Preterite: hice/hiciste/hizo/hicimos/hicieron" },
      { en: "Can / to be able to", es: "Poder", note: "Present: puedo/puedes/puede/podemos/pueden | Preterite: pude/pudiste/pudo/pudimos/pudieron" },
      { en: "To want", es: "Querer", note: "Present: quiero/quieres/quiere/queremos/quieren | Preterite: quise/quisiste/quiso/quisimos/quisieron" },
      { en: "To know (a fact)", es: "Saber", note: "Present: sé, sabes, sabe, sabemos, saben | Preterit: supe, supiste, supo, supimos, supieron" },
      { en: "To see / watch", es: "Ver", note: "Present: veo/ves/ve/vemos/ven | Preterite: vi/viste/vio/vimos/vieron" },
      { en: "To say / tell", es: "Decir", note: "Present: digo/dices/dice/decimos/dicen | Preterite: dije/dijiste/dijo/dijimos/dijeron" },
      { en: "To come", es: "Venir", note: "Present: vengo/vienes/viene/venimos/vienen | Preterite: vine/viniste/vino/vinimos/vinieron" },
      { en: "To put / place", es: "Poner", note: "Present: pongo/pones/pone/ponemos/ponen | Preterite: puse, pusiste, puso, pusimos, pusieron" },
      { en: "To leave / go out", es: "Salir", note: "Present: salgo/sales/sale/salimos/salen" },
      { en: "To bring", es: "Traer", note: "Present: traigo/traes/trae/traemos/traen | Preterite: traje, trajiste, trajo, trajimos, trajeron" },
      { en: "To give", es: "Dar", note: "Present: doy/das/da/damos/dan | Preterite: di/diste/dio/dimos/dieron" },
    ],
  },
  {
    name: "VERBS - common (pt. 1)",
    terms: [
      { en: "To eat", es: "Comer" },
      { en: "To drink", es: "Tomar" },
      { en: "To sleep", es: "Dormir", note: "present stem-change o→ue: duermo/duermes/duerme/dormimos/duermen | preterite stem-change in 3rd person: dormí/dormiste/durmió/dormimos/durmieron" },
      { en: "To walk", es: "Caminar" },
      { en: "To run", es: "Correr" },
      { en: "To work", es: "Trabajar" },
      { en: "To play", es: "Jugar", note: "present stem-change u→ue: juego/juegas/juega/jugamos/juegan | preterite yo spelling change: jugué/jugaste/jugó/jugamos/jugaron" },
      { en: "To study", es: "Estudiar" },
      { en: "To travel", es: "Viajar" },
      { en: "To leave", es: "Salir", note: "present irregular yo: salgo/sales/sale/salimos/salen" },
      { en: "To arrive", es: "Llegar", note: "preterite yo spelling change (g→gu): llegué/llegaste/llegó/llegamos/llegaron" },
      { en: "To buy", es: "Comprar" },
      { en: "To sell", es: "Vender" },
      { en: "To listen", es: "Escuchar" },
      { en: "To speak", es: "Hablar" },
      { en: "To watch", es: "Ver", note: "present irregular yo: veo/ves/ve/vemos/ven | preterite fully irregular: vi/viste/vio/vimos/vieron" },
      { en: "To read", es: "Leer", note: "preterite spelling change in 3rd person: leí/leíste/leyó/leímos/leyeron" },
      { en: "To write", es: "Escribir" },
      { en: "To think", es: "Pensar", note: "present stem-change e→ie: pienso/piensas/piensa/pensamos/piensan" },
      { en: "To know (a fact)", es: "Saber", note: "present irregular yo: sé/sabes/sabe/sabemos/saben | preterite fully irregular: supe/supiste/supo/supimos/supieron" },
    ],
  },
  {
    name: "VERBS - common (pt. 2)",
    terms: [
      { en: "To need", es: "Necesitar" },
      { en: "To have to / must", es: "Tener que" },
      { en: "To move", es: "Moverse", note: "present stem-change o→ue: me muevo/te mueves/se mueve/nos movemos/se mueven" },
      { en: "To change", es: "Cambiar" },
      { en: "To send", es: "Enviar", note: "present accent on the í: envío/envías/envía/enviamos/envían" },
      { en: "To receive", es: "Recibir" },
      { en: "To try", es: "Intentar" },
      { en: "To stop", es: "Parar" },
      { en: "To return", es: "Volver", note: "stem-change o→ue: vuelvo/vuelves/vuelve/volvemos/vuelven" },
      { en: "To put on / wear", es: "Ponerse", note: "present irregular yo: me pongo/te pones/se pone/nos ponemos/se ponen | preterite irregular: me puse/te pusiste/se puso/nos pusimos/se pusieron" },
      { en: "To take off", es: "Quitarse" },
      { en: "To wake up", es: "Despertarse", note: "present stem-change e→ie: me despierto/te despiertas/se despierta/nos despertamos/se despiertan" },
      { en: "To get dressed", es: "Vestirse", note: "present stem-change e→i: me visto/te vistes/se viste/nos vestimos/se visten | preterite stem-change in 3rd person: me vestí/te vestiste/se vistió/nos vestimos/se vistieron" },
      { en: "To feel", es: "Sentir", note: "present stem-change e→ie: siento/sientes/siente/sentimos/sienten | preterite stem-change in 3rd person: sentí/sentiste/sintió/sentimos/sintieron" },
      { en: "To want", es: "Querer", note: "stem-change e→ie: quiero/quieres/quiere/queremos/quieren" },
      { en: "To forget", es: "Olvidar" },
      { en: "To remember", es: "Recordar", note: "stem-change o→ue: recuerdo/recuerdas/recuerda/recordamos/recuerdan" },
      { en: "To understand", es: "Entender", note: "stem-change e→ie: entiendo/entiendes/entiende/entendemos/entienden" },
      { en: "To explain", es: "Explicar", note: "preterite yo spelling change (c→qu): expliqué/explicaste/explicó/explicamos/explicaron" },
      { en: "To help", es: "Ayudar" },
      { en: "To ask", es: "Preguntar" },
      { en: "To answer", es: "Contestar" },
      { en: "To call", es: "Llamar" },
      { en: "To wait", es: "Esperar" },
      { en: "To find", es: "Encontrar", note: "stem-change o→ue: encuentro/encuentras/encuentra/encontramos/encuentran" },
      { en: "To lose", es: "Perder", note: "stem-change e→ie: pierdo/pierdes/pierde/perdemos/pierden" },
      { en: "To win", es: "Ganar" },
      { en: "To pay", es: "Pagar", note: "preterite yo spelling change (g→gu): pagué/pagaste/pagó/pagamos/pagaron" },
      { en: "To open", es: "Abrir" },
      { en: "To close", es: "Cerrar", note: "stem-change e→ie: cierro/cierras/cierra/cerramos/cierran" },
      { en: "To start", es: "Empezar", note: "present stem-change e→ie: empiezo/empiezas/empieza/empezamos/empiezan | preterite yo spelling change (z→c): empecé/empezaste/empezó/empezamos/empezaron" },
      { en: "To continue", es: "Seguir", note: "present stem-change e→i: sigo/sigues/sigue/seguimos/siguen | preterite stem-change in 3rd person: seguí/seguiste/siguió/seguimos/siguieron" },
      { en: "To finish", es: "Terminar" },
    ],
  },
  {
    name: "VERBS - common (pt. 3)",
    terms: [
      { en: "To think", es: "Pensar", note: "irregular: pienso/piensas/piensa/pensamos/piensan" },
      { en: "To know (a fact)", es: "Saber", note: "irregular: sé/sabes/sabe/sabemos/saben" },
      { en: "To know (a person/place)", es: "Conocer", note: "irregular: conozco/conoces/conoce/conocemos/conocen" },
      { en: "To learn", es: "Aprender" },
      { en: "To study", es: "Estudiar" },
      { en: "To remember", es: "Recordar", note: "irregular: recuerdo/recuerdas/recuerda/recordamos/recuerdan" },
      { en: "To forget", es: "Olvidar" },
      { en: "To understand", es: "Entender", note: "irregular: entiendo/entiendes/entiende/entendemos/entienden" },
      { en: "To imagine", es: "Imaginar" },
      { en: "To believe", es: "Creer", note: "preterite spelling change in 3rd person: creí/creíste/creyó/creímos/creyeron" },
      { en: "To doubt", es: "Dudar" },
      { en: "To decide", es: "Decidir" },
      { en: "To choose", es: "Elegir", note: "present irregular: elijo/eliges/elige/elegimos/eligen | preterite stem-change in 3rd person: elegí/elegiste/eligió/elegimos/eligieron" },
      { en: "To plan", es: "Planear" },
      { en: "To focus", es: "Enfocarse", note: "preterite yo spelling change (c→qu): me enfoqué/te enfocaste/se enfocó/nos enfocamos/se enfocaron" },
      { en: "To practice", es: "Practicar", note: "preterite yo spelling change (c→qu): practiqué/practicaste/practicó/practicamos/practicaron" },
      { en: "To improve", es: "Mejorar" },
    ],
  },
  {
    name: "VERBS - common (pt. 4)",
    terms: [
      { en: "To use", es: "Usar" },
      { en: "To shower", es: "Ducharse" },
      { en: "To eat breakfast", es: "Desayunar" },
      { en: "To eat lunch", es: "Almorzar", note: "present stem-change o→ue: almuerzo/almuerzas/almuerza/almorzamos/almuerzan | preterite yo spelling change (z→c): almorcé/almorzaste/almorzó/almorzamos/almorzaron" },
      { en: "To eat dinner", es: "Cenar" },
      { en: "To cook", es: "Cocinar" },
      { en: "To clean", es: "Limpiar" },
      { en: "To wash", es: "Lavar" },
      { en: "To dry", es: "Secar", note: "preterite yo spelling change (c→qu): sequé/secaste/secó/secamos/secaron" },
      { en: "To stay", es: "Quedarse" },
      { en: "To drive", es: "Manejar" },
      { en: "To park", es: "Estacionar" },
      { en: "To walk (a pet)", es: "Pasear" },
      { en: "To exercise", es: "Ejercitarse" },
      { en: "To rest", es: "Descansar" },
      { en: "To enjoy", es: "Disfrutar" },
      { en: "To visit", es: "Visitar" },
      { en: "To meet (someone)", es: "Conocer", note: "present irregular yo: conozco/conoces/conoce/conocemos/conocen" },
      { en: "To take", es: "Llevar / Tomar", note: "Llevar = to transport/carry from pt. A to pt. B | Tomar = to grab an object, drink/eat something, catch public transport" },
      { en: "To hug", es: "Abrazar", note: "preterite yo spelling change (z→c): abracé/abrazaste/abrazó/abrazamos/abrazaron" },
      { en: "To hope", es: "Esperar" },
      { en: "To expect", es: "Esperar" },
    ],
  },
  {
    name: "VERBS - physical actions",
    terms: [
      { en: "To sit", es: "Sentarse", note: "present stem-change e→ie: me siento/te sientas/se sienta/nos sentamos/se sientan" },
      { en: "To stand up", es: "Levantarse" },
      { en: "To walk", es: "Caminar" },
      { en: "To run", es: "Correr" },
      { en: "To jump", es: "Saltar" },
      { en: "To throw", es: "Lanzar", note: "preterite yo spelling change: lancé/lanzaste/lanzó/lanzamos/lanzaron" },
      { en: "To kick", es: "Patear" },
      { en: "To punch", es: "Golpear" },
      { en: "To slap", es: "Abofetear" },
      { en: "To dance", es: "Bailar" },
      { en: "To swim", es: "Nadar" },
      { en: "To climb", es: "Escalar" },
      { en: "To fall", es: "Caerse", note: "present irregular yo: me caigo/te caes/se cae/nos caemos/se caen | preterite: me caí/te caíste/se cayó/nos caímos/se cayeron" },
      { en: "To push", es: "Empujar" },
      { en: "To pull", es: "Jalar" },
      { en: "To lift", es: "Levantar" },
      { en: "To carry", es: "Cargar", note: "preterite yo spelling change: cargué/cargaste/cargó/cargamos/cargaron" },
      { en: "To stretch", es: "Estirarse" },
      { en: "To crawl", es: "Gatear" },
    ],
  },

  // ---------------- ADJECTIVES ----------------
  {
    name: "ADJECTIVES - common (pt. 1)",
    terms: [
      { en: "Big", es: "Grande" },
      { en: "Small", es: "Pequeño / Pequeña" },
      { en: "Tall", es: "Alto / Alta" },
      { en: "Short", es: "Bajo / Baja" },
      { en: "Fast", es: "Rápido / Rápida" },
      { en: "Slow", es: "Lento / Lenta" },
      { en: "Strong", es: "Fuerte" },
      { en: "Weak", es: "Débil" },
      { en: "Beautiful", es: "Hermoso / Hermosa" },
      { en: "Ugly", es: "Feo / Fea" },
      { en: "Young", es: "Joven" },
      { en: "Old", es: "Viejo / Vieja" },
      { en: "Rich", es: "Rico / Rica" },
      { en: "Poor", es: "Pobre" },
      { en: "Easy", es: "Fácil" },
      { en: "Difficult", es: "Difícil" },
      { en: "Interesting", es: "Interesante" },
      { en: "Boring", es: "Aburrido / Aburrida" },
      { en: "Funny", es: "Gracioso / Graciosa" },
      { en: "Serious", es: "Serio / Seria" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 2) - colors",
    terms: [
      { en: "Red", es: "Rojo / Roja" },
      { en: "Blue", es: "Azul" },
      { en: "Green", es: "Verde" },
      { en: "Yellow", es: "Amarillo / Amarilla" },
      { en: "Orange", es: "Anaranjado / Anaranjada" },
      { en: "Purple", es: "Morado / Morada" },
      { en: "Pink", es: "Rosado / Rosada" },
      { en: "White", es: "Blanco / Blanca" },
      { en: "Gray", es: "Gris" },
      { en: "Brown", es: "Café" },
      { en: "Dark", es: "Oscuro / Oscura" },
      { en: "Light", es: "Claro / Clara" },
      { en: "Black", es: "Negro / Negra" },
      { en: "Gold", es: "Oro" },
      { en: "Silver", es: "Plata" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 3) - feelings",
    terms: [
      { en: "Happy", es: "Feliz" },
      { en: "Sad", es: "Triste" },
      { en: "Depressed", es: "Deprimido / Deprimida" },
      { en: "Angry", es: "Enojado / Enojada" },
      { en: "Confused", es: "Confundido / Confundida" },
      { en: "Tired", es: "Cansado / Cansada" },
      { en: "Alert", es: "Alerta" },
      { en: "Bored", es: "Aburrido / Aburrida" },
      { en: "Afraid", es: "Asustado / Asustada" },
      { en: "Stressed", es: "Estresado / Estresada" },
      { en: "Confident", es: "Seguro / Segura (de sí mismo)" },
      { en: "Anxious", es: "Ansioso / Ansiosa" },
      { en: "Nervous", es: "Nervioso / Nerviosa" },
      { en: "Curious", es: "Curioso / Curiosa" },
      { en: "Jealous", es: "Celoso / Celosa" },
      { en: "Excited", es: "Emocionado / Emocionada" },
      { en: "Calm", es: "Tranquilo / Tranquila" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 4)",
    terms: [
      { en: "Full", es: "Lleno / Llena" },
      { en: "Empty", es: "Vacío / Vacía" },
      { en: "Clean", es: "Limpio / Limpia" },
      { en: "Dirty", es: "Sucio / Sucia" },
      { en: "Hot", es: "Caliente" },
      { en: "Cold", es: "Frío / Fría" },
      { en: "New", es: "Nuevo / Nueva" },
      { en: "Same", es: "Mismo / Misma" },
      { en: "Different", es: "Diferente" },
      { en: "Open", es: "Abierto / Abierta" },
      { en: "Closed", es: "Cerrado / Cerrada" },
      { en: "Free (available)", es: "Libre" },
      { en: "Busy", es: "Ocupado / Ocupada" },
      { en: "Near", es: "Cerca" },
      { en: "Far", es: "Lejos" },
      { en: "Right", es: "Correcto / Correcta" },
      { en: "Wrong", es: "Incorrecto / Incorrecta" },
      { en: "Ready", es: "Listo / Lista" },
      { en: "Loud", es: "Ruidoso / Ruidosa" },
      { en: "Quiet", es: "Silencioso / Silenciosa" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 5)",
    terms: [
      { en: "Healthy", es: "Sano / Sana" },
      { en: "Sick", es: "Enfermo / Enferma" },
      { en: "Drunk", es: "Borracho / Borracha" },
      { en: "Sober", es: "Sobrio / Sobria" },
      { en: "Hungry", es: "Hambriento / Hambrienta" },
      { en: "Thirsty", es: "Sediento / Sedienta" },
      { en: "Sleepy", es: "Somnoliento / Somnolienta" },
      { en: "Alive", es: "Vivo / Viva" },
      { en: "Dead", es: "Muerto / Muerta" },
      { en: "Lost", es: "Perdido / Perdida" },
      { en: "Safe", es: "Seguro / Segura" },
      { en: "Dangerous", es: "Peligroso / Peligrosa" },
      { en: "Alone", es: "Solo / Sola" },
      { en: "Together", es: "Juntos / Juntas" },
      { en: "Possible", es: "Posible" },
      { en: "Impossible", es: "Imposible" },
      { en: "Necessary", es: "Necesario / Necesaria" },
      { en: "Important", es: "Importante" },
      { en: "Normal", es: "Normal" },
      { en: "Strange", es: "Extraño / Extraña" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 6)",
    terms: [
      { en: "Comfortable", es: "Cómodo / Cómoda" },
      { en: "Uncomfortable", es: "Incómodo / Incómoda" },
      { en: "Expensive", es: "Caro / Cara" },
      { en: "Cheap", es: "Barato / Barata" },
      { en: "Heavy", es: "Pesado / Pesada" },
      { en: "Light (weight)", es: "Ligero / Ligera" },
      { en: "Delicious", es: "Delicioso / Deliciosa" },
      { en: "Disgusting", es: "Asqueroso / Asquerosa" },
      { en: "Spicy", es: "Picante" },
      { en: "Sweet", es: "Dulce" },
      { en: "Sour", es: "Agrio / Agria" },
      { en: "Salty", es: "Salado / Salada" },
      { en: "Loud (person/personality)", es: "Escandaloso / Escandalosa" },
      { en: "Friendly", es: "Amigable" },
      { en: "Kind", es: "Amable" },
      { en: "Rude", es: "Grosero / Grosera" },
      { en: "Polite", es: "Educado / Educada" },
      { en: "Honest", es: "Honesto / Honesta" },
      { en: "Patient", es: "Paciente" },
      { en: "Impatient", es: "Impaciente" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 7)",
    terms: [
      { en: "Skinny", es: "Delgado / Delgada" },
      { en: "Fat", es: "Gordo / Gorda" },
      { en: "Muscular", es: "Musculoso / Musculosa" },
      { en: "Bald", es: "Calvo / Calva" },
      { en: "Handsome", es: "Guapo / Guapa" },
      { en: "Pretty", es: "Bonito / Bonita" },
      { en: "Cute", es: "Lindo / Linda" },
      { en: "Shy", es: "Tímido / Tímida" },
      { en: "Outgoing", es: "Extrovertido / Extrovertida" },
      { en: "Lazy", es: "Perezoso / Perezosa" },
      { en: "Hardworking", es: "Trabajador / Trabajadora" },
      { en: "Generous", es: "Generoso / Generosa" },
      { en: "Selfish", es: "Egoísta" },
      { en: "Smart", es: "Inteligente" },
      { en: "Stupid", es: "Tonto / Tonta" },
      { en: "Creative", es: "Creativo / Creativa" },
      { en: "Talented", es: "Talentoso / Talentosa" },
      { en: "Responsible", es: "Responsable" },
      { en: "Irresponsible", es: "Irresponsable" },
      { en: "Mature", es: "Maduro / Madura" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 8)",
    terms: [
      { en: "Enough", es: "Suficiente" },
      { en: "More", es: "Más" },
      { en: "Less", es: "Menos" },
      { en: "A lot / Much", es: "Mucho / Mucha" },
      { en: "A little", es: "Poco / Poca" },
      { en: "All / Every", es: "Todo / Toda" },
      { en: "Better", es: "Mejor" },
      { en: "Worse", es: "Peor" },
      { en: "First", es: "Primero / Primera" },
      { en: "Last", es: "Último / Última" },
      { en: "Next", es: "Próximo / Próxima" },
      { en: "Whole / Entire", es: "Entero / Entera" },
      { en: "Wide", es: "Ancho / Ancha" },
      { en: "Narrow", es: "Estrecho / Estrecha" },
      { en: "Deep", es: "Profundo / Profunda" },
      { en: "Shallow", es: "Poco profundo" },
      { en: "Sharp", es: "Afilado / Afilada" },
      { en: "Dull (not sharp)", es: "Desafilado / Desafilada" },
      { en: "Round", es: "Redondo / Redonda" },
      { en: "Square", es: "Cuadrado / Cuadrada" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 9)",
    terms: [
      { en: "Free (no cost)", es: "Gratis" },
      { en: "Public", es: "Público / Pública" },
      { en: "Private", es: "Privado / Privada" },
      { en: "Common", es: "Común" },
      { en: "Rare", es: "Raro / Rara" },
      { en: "Modern", es: "Moderno / Moderna" },
      { en: "Ancient", es: "Antiguo / Antigua" },
      { en: "Local", es: "Local" },
      { en: "Foreign", es: "Extranjero / Extranjera" },
      { en: "National", es: "Nacional" },
      { en: "International", es: "Internacional" },
      { en: "Legal", es: "Legal" },
      { en: "Illegal", es: "Ilegal" },
      { en: "Real", es: "Real" },
      { en: "Fake", es: "Falso / Falsa" },
      { en: "Complete", es: "Completo / Completa" },
      { en: "Incomplete", es: "Incompleto / Incompleta" },
      { en: "Available", es: "Disponible" },
      { en: "Unavailable", es: "No disponible" },
      { en: "Popular", es: "Popular" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 10)",
    terms: [
      { en: "Single (relationship status)", es: "Soltero / Soltera" },
      { en: "Married", es: "Casado / Casada" },
      { en: "Divorced", es: "Divorciado / Divorciada" },
      { en: "Pregnant", es: "Embarazada" },
      { en: "Adult", es: "Adulto / Adulta" },
      { en: "Elderly", es: "Anciano / Anciana" },
      { en: "Blind", es: "Ciego / Ciega" },
      { en: "Deaf", es: "Sordo / Sorda" },
      { en: "Injured", es: "Herido / Herida" },
      { en: "Broken", es: "Roto / Rota" },
      { en: "Fixed", es: "Arreglado / Arreglada" },
      { en: "Wet", es: "Mojado / Mojada" },
      { en: "Dry", es: "Seco / Seca" },
      { en: "Cunning", es: "Astuto / Astuta" },
      { en: "Wise", es: "Sabio / Sabia" },
      { en: "Brave", es: "Valiente" },
      { en: "Cowardly", es: "Cobarde" },
      { en: "Cruel", es: "Cruel" },
      { en: "Gentle", es: "Suave" },
      { en: "Loyal", es: "Leal" },
    ],
  },
  {
    name: "ADJECTIVES - common (pt. 11)",
    terms: [
      { en: "Favorite", es: "Favorito / Favorita" },
      { en: "Least favorite", es: "Menos favorito / Menos favorita" },
      { en: "Average", es: "Promedio" },
      { en: "Humid", es: "Húmedo / Húmeda" },
      { en: "Obsessed", es: "Obsesionado / Obsesionada" },
      { en: "Addicted", es: "Adicto / Adicta" },
      { en: "Evil", es: "Malvado / Malvada" },
      { en: "Attractive", es: "Atractivo / Atractiva" },
      { en: "Smooth", es: "Suave" },
      { en: "Rough", es: "Áspero / Áspera" },
      { en: "Cool (temperature)", es: "Fresco / Fresca" },
      { en: "Online", es: "En línea" },
      { en: "Offline", es: "Fuera de línea" },
      { en: "Useful", es: "Útil" },
      { en: "Arrogant", es: "Arrogante" },
      { en: "Humble", es: "Humilde" },
      { en: "Masculine", es: "Masculino" },
      { en: "Feminine", es: "Femenino" },
      { en: "Athletic", es: "Atlético / Atlética" },
      { en: "Artistic", es: "Artístico / Artística" },
      { en: "Bad", es: "Malo / Mala" },
      { en: "Good", es: "Bueno / Buena" },
    ],
  },

  // ---------------- MISC ----------------
  {
    name: "MISC - time words",
    terms: [
      { en: "Monday", es: "lunes" },
      { en: "Tuesday", es: "martes" },
      { en: "Wednesday", es: "miércoles" },
      { en: "Thursday", es: "jueves" },
      { en: "Friday", es: "viernes" },
      { en: "Saturday", es: "sábado" },
      { en: "Sunday", es: "domingo" },
      { en: "January", es: "enero" },
      { en: "February", es: "febrero" },
      { en: "March", es: "marzo" },
      { en: "April", es: "abril" },
      { en: "May", es: "mayo" },
      { en: "June", es: "junio" },
      { en: "July", es: "julio" },
      { en: "August", es: "agosto" },
      { en: "September", es: "septiembre" },
      { en: "October", es: "octubre" },
      { en: "November", es: "noviembre" },
      { en: "December", es: "diciembre" },
      { en: "Minute", es: "el minuto" },
      { en: "Hour", es: "la hora" },
      { en: "Day", es: "El día" },
      { en: "Week", es: "La semana" },
      { en: "Month", es: "el mes" },
      { en: "Year", es: "el año" },
      { en: "Yesterday", es: "ayer" },
      { en: "Today", es: "hoy" },
      { en: "Tomorrow", es: "mañana" },
      { en: "Last week", es: "la semana pasada" },
      { en: "This week", es: "esta semana" },
      { en: "Next week", es: "la semana que viene" },
      { en: "Last year", es: "el año pasado" },
      { en: "This year", es: "este año" },
      { en: "Next year", es: "el año que viene" },
      { en: "Morning", es: "la mañana" },
      { en: "afternoon", es: "la tarde" },
      { en: "Night", es: "la noche" },
      { en: "Now", es: "ahora" },
      { en: "Right now", es: "ahora mismo" },
      { en: "Soon", es: "pronto" },
      { en: "Later", es: "más tarde" },
      { en: "Always", es: "siempre" },
      { en: "Never", es: "nunca" },
      { en: "Sometimes", es: "a veces" },
      { en: "Already", es: "ya" },
      { en: "Still", es: "todavía" },
      { en: "Early", es: "temprano" },
      { en: "Late", es: "tarde" },
      { en: "Before", es: "antes" },
      { en: "During", es: "durante" },
      { en: "After", es: "después" },
      { en: "While", es: "mientras" },
      { en: "When", es: "cuándo" },
      { en: "Since", es: "desde" },
      { en: "Until", es: "hasta" },
      { en: "Again", es: "otra vez" },
      { en: "Finally", es: "por fin" },
      { en: "Second", es: "El segundo" },
      { en: "Last night", es: "anoche" },
      { en: "Tonight", es: "esta noche" },
      { en: "Tomorrow night", es: "mañana por la noche" },
      { en: "Yesterday morning", es: "ayer por la mañana" },
      { en: "This morning", es: "esta mañana" },
      { en: "Tomorrow morning", es: "mañana por la mañana" },
      { en: "Yesterday afternoon", es: "ayer por la tarde" },
      { en: "This afternoon", es: "esta tarde" },
      { en: "Tomorrow afternoon", es: "mañana por la tarde" },
      { en: "Every", es: "cada" },
      { en: "(to do something) in the morning", es: "por la mañana" },
      { en: "(to do something) in the afternoon", es: "por la tarde" },
      { en: "(to do something) at night", es: "por la noche" },
      { en: "(some time, like clock) in the morning", es: "de la mañana" },
      { en: "(some time, like clock) in the afternoon", es: "de la tarde" },
      { en: "(some time, like clock) at night", es: "de la noche" },
      { en: "All morning", es: "toda la mañana" },
      { en: "All afternoon", es: "toda la tarde" },
      { en: "All night", es: "toda la noche" },
      { en: "All day", es: "todo el día" },
      { en: "Up until now", es: "hasta ahora" },
    ],
  },
  {
    name: "MISC - gustar-type verbs & pronouns",
    terms: [
      { en: "To be pleasing to (to like)", es: "Gustar", note: "Present: gusta / gustan | Preterite: gustó / gustaron" },
      { en: "To be enchanting to (to love)", es: "Encantar", note: "Present: encanta / encantan | Preterite: encantó / encantaron" },
      { en: "To interest", es: "Interesar", note: "Present: interesa / interesan | Preterite: interesó / interesaron" },
      { en: "To cause pain to (to hurt)", es: "Doler", note: "Present: duele / duelen | Preterite: dolió / dolieron" },
      { en: "My / his / her / your (formal) / our", es: "mi(s) / su(s) / nuestro(s) / nuestra(s)" },
      { en: "Indirect object pronouns", es: "me / te / le / nos / les" },
    ],
  },
  {
    name: "MISC - numbers",
    terms: [
      { en: "1", es: "uno" },
      { en: "2", es: "dos" },
      { en: "3", es: "tres" },
      { en: "4", es: "cuatro" },
      { en: "5", es: "cinco" },
      { en: "6", es: "seis" },
      { en: "7", es: "siete" },
      { en: "8", es: "ocho" },
      { en: "9", es: "nueve" },
      { en: "10", es: "diez" },
      { en: "11", es: "once" },
      { en: "12", es: "doce" },
      { en: "13", es: "trece" },
      { en: "14", es: "catorce" },
      { en: "15", es: "quince" },
      { en: "16", es: "dieciséis" },
      { en: "17", es: "diecisiete" },
      { en: "18", es: "dieciocho" },
      { en: "19", es: "diecinueve" },
      { en: "20", es: "veinte" },
      { en: "21", es: "veintiuno" },
      { en: "30", es: "treinta" },
      { en: "32", es: "treinta y dos" },
      { en: "40", es: "cuarenta" },
      { en: "43", es: "cuarenta y tres" },
      { en: "50", es: "cincuenta" },
      { en: "54", es: "cincuenta y cuatro" },
      { en: "60", es: "sesenta" },
      { en: "65", es: "sesenta y cinco" },
      { en: "70", es: "setenta" },
      { en: "76", es: "setenta y seis" },
      { en: "80", es: "ochenta" },
      { en: "87", es: "ochenta y siete" },
      { en: "90", es: "noventa" },
      { en: "98", es: "noventa y ocho" },
      { en: "100", es: "cien" },
      { en: "101", es: "ciento uno" },
      { en: "123", es: "ciento veintitrés" },
      { en: "200", es: "doscientos" },
      { en: "234", es: "doscientos treinta y cuatro" },
      { en: "300", es: "trescientos" },
      { en: "345", es: "trescientos cuarenta y cinco" },
      { en: "400", es: "cuatrocientos" },
      { en: "500", es: "quinientos" },
      { en: "600", es: "seiscientos" },
      { en: "700", es: "setecientos" },
      { en: "800", es: "ochocientos" },
      { en: "900", es: "novecientos" },
      { en: "1,000", es: "mil" },
      { en: "1,234", es: "mil doscientos treinta y cuatro" },
      { en: "2,000", es: "dos mil" },
      { en: "2,341", es: "dos mil trescientos cuarenta y uno" },
    ],
  },
  {
    name: "MISC - question words",
    terms: [
      { en: "What", es: "Qué" },
      { en: "Who", es: "Quién" },
      { en: "Where", es: "Dónde" },
      { en: "When", es: "Cuándo" },
      { en: "Why", es: "Por qué" },
      { en: "How", es: "Cómo" },
      { en: "How much", es: "Cuánto" },
      { en: "How many", es: "Cuántos" },
      { en: "Which", es: "Cuál" },
      { en: "Where to", es: "Adónde" },
    ],
  },
  {
    name: "MISC - common questions",
    terms: [
      { en: "What is your name?", es: "¿Cómo te llamas? / ¿Cuál es tu nombre?" },
      { en: "How are you?", es: "¿Cómo estás? / ¿Qué tal?" },
      { en: "Where are you from?", es: "¿De dónde eres?" },
      { en: "Where do you live?", es: "¿Dónde vives?" },
      { en: "How old are you?", es: "¿Cuántos años tienes?" },
      { en: "What time is it?", es: "¿Qué hora es?" },
      { en: "What do you want?", es: "¿Qué quieres?" },
      { en: "Where is the bathroom?", es: "¿Dónde está el baño?" },
      { en: "How much does it cost?", es: "¿Cuánto cuesta? / ¿Cuánto es?" },
      { en: "What are you doing?", es: "¿Qué haces? / ¿Qué estás haciendo?" },
      { en: "Do you speak English?", es: "¿Hablas inglés?" },
      { en: "Can you help me?", es: "¿Puedes ayudarme? / ¿Me puedes ayudar?" },
      { en: "What does it mean?", es: "¿Qué significa?" },
      { en: "Where are we going?", es: "¿Adónde vamos?" },
      { en: "Who is he?", es: "¿Quién es él?" },
      { en: "Why not?", es: "¿Por qué no?" },
      { en: "When do we leave?", es: "¿Cuándo salimos?" },
      { en: "Which one do you want?", es: "¿Cuál quieres?" },
      { en: "What happened?", es: "¿Qué pasó?" },
      { en: "Do you have the money?", es: "¿Tienes el dinero?" },
      { en: "How many people are there?", es: "¿Cuántas personas hay?" },
      { en: "Are you ready?", es: "¿Estás listo? / ¿Estás lista?" },
      { en: "Do you understand?", es: "¿Entiendes? / ¿Comprendes?" },
      { en: "Where is the hotel?", es: "¿Dónde está el hotel?" },
      { en: "What is this?", es: "¿Qué es esto?" },
    ],
  },
  {
    name: "MISC - connecting words (pt. 1)",
    terms: [
      { en: "But", es: "Pero" },
      { en: "Although", es: "Aunque" },
      { en: "Because", es: "Porque" },
      { en: "So / Therefore", es: "Entonces" },
      { en: "Also", es: "También" },
      { en: "Neither / Not either", es: "Tampoco" },
      { en: "And", es: "Y" },
      { en: "Or", es: "O" },
      { en: "If", es: "Si" },
      { en: "That", es: "Que" },
      { en: "So that", es: "Para que" },
      { en: "Without", es: "Sin" },
      { en: "With", es: "Con" },
      { en: "Against", es: "Contra" },
      { en: "Instead of", es: "En vez de" },
      { en: "As soon as", es: "En cuanto" },
      { en: "As long as", es: "Mientras que" },
      { en: "Even though", es: "Aunque" },
      { en: "However", es: "Sin embargo" },
      { en: "In fact", es: "De hecho" },
      { en: "For example", es: "Por ejemplo" },
    ],
  },
  {
    name: "MISC - prepositions",
    terms: [
      { en: "In / On / At (general)", es: "En" },
      { en: "To / At (direction)", es: "A" },
      { en: "Of / From", es: "De" },
      { en: "With", es: "Con" },
      { en: "Without", es: "Sin" },
      { en: "For (recipient/purpose)", es: "Para" },
      { en: "For (duration/exchange/on behalf of)", es: "Por" },
      { en: "Between", es: "Entre" },
      { en: "Behind", es: "Detrás de" },
      { en: "In front of", es: "Delante de" },
      { en: "Under", es: "Debajo de" },
      { en: "On top of / Above", es: "Encima de" },
      { en: "Next to", es: "Al lado de" },
      { en: "Inside", es: "Dentro de" },
      { en: "Outside", es: "Fuera de" },
      { en: "Near", es: "Cerca de" },
      { en: "Far from", es: "Lejos de" },
      { en: "Toward", es: "Hacia" },
      { en: "Against", es: "Contra" },
      { en: "Through / By", es: "Por" },
      { en: "Up to / Until", es: "Hasta" },
      { en: "Since / From (time)", es: "Desde" },
      { en: "About (topic)", es: "Sobre" },
      { en: "Around", es: "Alrededor de" },
      { en: "A + el (contraction)", es: "Al" },
      { en: "De + el (contraction)", es: "Del" },
      { en: "Except", es: "Excepto" },
    ],
  },
  // {
  //   name: "MISC - pronouns (all types)",
  //   terms: [
  //     { en: "I", es: "Yo" },
  //     { en: "You", es: "Tú" },
  //     { en: "He", es: "Él" },
  //     { en: "She", es: "Ella" },
  //     { en: "We", es: "Nosotros / Nosotras" },
  //     { en: "They", es: "Ellos / Ellas" },
  //     { en: "Me (object)", es: "Me" },
  //     { en: "You (object)", es: "Te" },
  //     { en: "Him (object)", es: "Lo" },
  //     { en: "Her (object)", es: "La" },
  //     { en: "It (object)", es: "Lo / La" },
  //     { en: "Us (object)", es: "Nos" },
  //     { en: "Them (object)", es: "Los / Las" },
  //     { en: "My", es: "Mi / Mis" },
  //     { en: "Your", es: "Tu / Tus" },
  //     { en: "His / Her / Their", es: "Su / Sus" },
  //     { en: "Our", es: "Nuestro / Nuestra / Nuestros / Nuestras" },
  //     { en: "Mine", es: "Mío / Mía / Míos / Mías" },
  //     { en: "Yours", es: "Tuyo / Tuya / Tuyos / Tuyas" },
  //     { en: "His / Hers / Theirs", es: "Suyo / Suya / Suyos / Suyas" },
  //     { en: "Ours", es: "Nuestro / Nuestra / Nuestros / Nuestras" },
  //     { en: "It (object)", es: "Lo / La" },
  //     { en: "To him / to her / to you (formal)", es: "Le" },
  //     { en: "To them / to you all", es: "Les" },
  //     { en: "This", es: "Este / Esta" },
  //     { en: "That", es: "Ese / Esa" },
  //     { en: "These", es: "Estos / Estas" },
  //     { en: "Those", es: "Esos / Esas" },
  //   ],
  // },
  {
    "name": "PRONOUNS - Subject (The Doers)",
    "terms": [
      { "en": "I", "es": "Yo" },
      { "en": "You (informal)", "es": "Tú" },
      { "en": "He", "es": "Él" },
      { "en": "She", "es": "Ella" },
      { "en": "We", "es": "Nosotros / Nosotras" },
      { "en": "They", "es": "Ellos / Ellas" },
      { "en": "You (formal)", "es": "Usted" },
      { "en": "You all", "es": "Ustedes" }
    ]
  },
  {
    "name": "PRONOUNS - Direct Object (The Receivers)",
    "terms": [
      { "en": "Me", "es": "Me" },
      { "en": "You", "es": "Te" },
      { "en": "Him / It", "es": "Lo" },
      { "en": "Her / It", "es": "La" },
      { "en": "Us", "es": "Nos" },
      { "en": "Them (masculine)", "es": "Los" },
      { "en": "Them (feminine)", "es": "Las" }
    ]
  },
  {
    "name": "PRONOUNS - Indirect Object (To/For whom)",
    "terms": [
      { "en": "To me", "es": "Me" },
      { "en": "To you", "es": "Te" },
      { "en": "To him / her / you formal", "es": "Le" },
      { "en": "To us", "es": "Nos" },
      { "en": "To them / you all", "es": "Les" }
    ]
  },
  {
    "name": "PRONOUNS - Possessive (My, Your, His...)",
    "terms": [
      { "en": "My", "es": "Mi / Mis" },
      { "en": "Your", "es": "Tu / Tus" },
      { "en": "His / Her / Its / Their", "es": "Su / Sus" },
      { "en": "Our", "es": "Nuestro / Nuestra / Nuestros / Nuestras" }
    ]
  },
  {
    "name": "PRONOUNS - Possessive (Mine, Yours, His...)",
    "terms": [
      { "en": "Mine", "es": "Mío / Mía / Míos / Mías" },
      { "en": "Yours", "es": "Tuyo / Tuya / Tuyos / Tuyas" },
      { "en": "His / Hers / Theirs", "es": "Suyo / Suya / Suyos / Suyas" },
      { "en": "Ours", "es": "Nuestro / Nuestra / Nuestros / Nuestras" }
    ]
  },
  {
    "name": "PRONOUNS - Demonstrative (This, That, These, Those)",
    "terms": [
      { "en": "This", "es": "Este / Esta" },
      { "en": "That", "es": "Ese / Esa" },
      { "en": "These", "es": "Estos / Estas" },
      { "en": "Those", "es": "Esos / Esas" }
    ]
  },
  {
    name: "MISC - adverb rules",
    terms: [
      {
        en: "Adverbs describing actions",
        es: "Use masculine singular adjective form regardless of gender when it describes HOW an action is done",
        note: "e.g. La niña corre rápido (not rápida). El hombre habla claro.",
      },
      {
        en: "-mente adverbs",
        es: "Add -mente to the feminine adjective form (Spanish's -ly)",
        note: "rápida→rápidamente, lenta→lentamente, tranquila→tranquilamente. Both forms are correct; the short form is more casual.",
      },
    ],
  },
];
